# Cleaning Data using Pandas

- **3.1 Overview of Pandas**
    - 3.1.1 Loading Library

- **3.2 Date Structure of Pandas**
    - 3.2.1 Series Object
    - 3.2.2 DataFrame Object

- **3.3 Loading and Interacting with Data**
    - 3.3.1 Downloading Data from the Internet
    - 3.3.2 Data Loading and Checking Data

- **3.4 DataFrame Basics**
    - 3.4.1 Data Selection and Assignment
    - 3.4.2 Extracting Data with Specific Conditions
    - 3.4.3 Determination of nan (null)
    - 3.4.4 Sorting of Values
- **3.5 Merging and Concatenating Data**
    - 3.5.1 Merging Data
    - 3.5.2 Concatenating Data
- **3.6 Manipulating and Transforming Data**
    - 3.6.1 Deleting Data
    - 3.6.2 Removing Duplicates
    - 3.6.3 Mapping
    - 3.6.4 Bin Splitting
- **3.7 Aggregating Data**
- **3.8 Advanced: Hierarchical Grouping**
- **3.9 Advanced: Handling Missing or Anomalous Data**
    - 3.9.1 How to Handle Missing Data
    - 3.9.2 How to Handle Anomaly Data
- **3.10 Comprehensive Question**

In [5]:
import pandas as pd
import numpy as np
import numpy.random as random
from pandas import Series, DataFrame
import matplotlib.pyplot as plt

In [6]:
# Alphabetize the index
series_i = Series(
    [1, 1, 2, 3, 5, 8, 13],
    index=['a', 'b', 'c', 'd', 'e', 'f','g']
)

print(series_i)

a     1
b     1
c     2
d     3
e     5
f     8
g    13
dtype: int64

In [7]:
print('Element:', series_i.values)
print('index:', series_i.index)

Element: [ 1  1  2  3  5  8 13]
index: Index(['a', 'b', 'c', 'd', 'e', 'f', 'g'], dtype='object')

# DataFrame Objects

In [8]:
data = {
    'ID':['100', '101', '102', '103', '104'],
    'City':['Tokyo', 'Osaka', 'Kyoto', 'Hokkaido', 'Tokyo'],
    'Birth_year':[1990, 1989, 1992, 1997, 1982],
    'Name':['Hiroshi', 'Akiko', 'Yuki', 'Satoru', 'Steve']
}

df = DataFrame(data)

print(df)

    ID      City  Birth_year     Name
0  100     Tokyo        1990  Hiroshi
1  101     Osaka        1989    Akiko
2  102     Kyoto        1992     Yuki
3  103  Hokkaido        1997   Satoru
4  104     Tokyo        1982    Steve

In [10]:
df.columns

Index(['ID', 'City', 'Birth_year', 'Name'], dtype='object')

In [11]:
df["ID"]

0    100
1    101
2    102
3    103
4    104
Name: ID, dtype: object

In [12]:
df["City"]

0       Tokyo
1       Osaka
2       Kyoto
3    Hokkaido
4       Tokyo
Name: City, dtype: object

In [13]:
df.iloc[0:1]

    ID   City  Birth_year     Name
0  100  Tokyo        1990  Hiroshi

In [15]:
df.shape

(5, 4)

In [14]:
df.iloc[0:4]

    ID      City  Birth_year     Name
0  100     Tokyo        1990  Hiroshi
1  101     Osaka        1989    Akiko
2  102     Kyoto        1992     Yuki
3  103  Hokkaido        1997   Satoru

In [16]:
df.iloc[1:3,1:3]

    City  Birth_year
1  Osaka        1989
2  Kyoto        1992

In [17]:
df.head()

    ID      City  Birth_year     Name
0  100     Tokyo        1990  Hiroshi
1  101     Osaka        1989    Akiko
2  102     Kyoto        1992     Yuki
3  103  Hokkaido        1997   Satoru
4  104     Tokyo        1982    Steve

In [18]:
df_i = DataFrame(data, index=['a', 'b', 'c', 'd', 'e'])
print(df_i)

    ID      City  Birth_year     Name
a  100     Tokyo        1990  Hiroshi
b  101     Osaka        1989    Akiko
c  102     Kyoto        1992     Yuki
d  103  Hokkaido        1997   Satoru
e  104     Tokyo        1982    Steve

In [22]:
df_i.iloc[1:3,1:3]

    City  Birth_year
b  Osaka        1989
c  Kyoto        1992

In [26]:
df_i.iloc[1]

ID              101
City          Osaka
Birth_year     1989
Name          Akiko
Name: b, dtype: object

In [27]:
print('Element:', df_i.values)
print('Index:', df_i.index)
print('Column:', df_i.columns)

Element: [['100' 'Tokyo' 1990 'Hiroshi']
 ['101' 'Osaka' 1989 'Akiko']
 ['102' 'Kyoto' 1992 'Yuki']
 ['103' 'Hokkaido' 1997 'Satoru']
 ['104' 'Tokyo' 1982 'Steve']]
Index: Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
Column: Index(['ID', 'City', 'Birth_year', 'Name'], dtype='object')

In [32]:
df.describe() # concider only neumerical values

       Birth_year
count     5.00000
mean   1990.00000
std       5.43139
min    1982.00000
25%    1989.00000
50%    1990.00000
75%    1992.00000
max    1997.00000

In [33]:
df_i

    ID      City  Birth_year     Name
a  100     Tokyo        1990  Hiroshi
b  101     Osaka        1989    Akiko
c  102     Kyoto        1992     Yuki
d  103  Hokkaido        1997   Satoru
e  104     Tokyo        1982    Steve

In [34]:
#Specify the maximum number of columns to display
pd.set_option('display.max_columns', 50)
#Specify the maximum number of rows to display
pd.set_option('display.max_rows', 10)

# Dataset Description

In [35]:
# Libraries for retrieving data from the web and handling zip files
import requests, zipfile
from io import StringIO
import io

In [36]:
# Specify the url with data
url = 'https://github.com/Hernan4444/MyAnimeList-Database/archive/refs/heads/master.zip'

# Acquire data from the url
r = requests.get(url, stream=True)

# read and extract the zipfile
z = zipfile.ZipFile(io.BytesIO(r.content))
z.extractall()

In [37]:
# !sudo apt-get install tree

Sudo is disabled on this machine. To enable it, go to the ]8;;ms-settings:developers\Developer Settings page]8;;\ in the Settings app

In [38]:
# !pip apt-get install tree

ERROR: unknown command "apt-get"

In [39]:
!pip install tree

Collecting tree
  Downloading Tree-0.2.4.tar.gz (6.5 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: Pillow in c:\users\hp\miniconda3\envs\pytorch\lib\site-packages (from tree) (12.0.0)
Collecting svgwrite (from tree)
  Downloading svgwrite-1.4.3-py3-none-any.whl.metadata (8.8 kB)
Requirement already satisfied: setuptools in c:\users\hp\miniconda3\envs\pytorch\lib\site-packages (from tree) (80.9.0)
Collecting click (from tree)
  Downloading click-8.5.0-py3-none-any.whl.metadata (2.6 kB)
Downloading click-8.5.0-py3-none-any.whl (125 kB)
Downloading svgwrite-1.4.3-py3-none-any.whl (67 kB)
Building wheels for collected packages: tree
  Building wheel for tree (pyproject.toml): started
  Building wheel for tree (pyproject.toml): finished with status 'done'
  Created wheel for tree: filename=tree-0.2.4-py3-none-any.whl size=7919 sha256=0e3b7265c8d372965dc363566fd4bb2d12a5f5da9746d5c247c6ec82639e7fb3
  Stored in directory: c:\users\hp\appdata\local\pip\cache\wheels\0d\b8\ca\bf432f4ef2a525e65b33da2bef014a06a0791cae6b448dc0e2
Successfully built tree
Installing collected packages: svgwrite, click, tree

   ------------- -------------------------- 1/3 [click]
   ---------------------------------------- 3/3 [tree]

Successfully installed click-8.5.0 svgwrite-1.4.3 tree-0.2.4

In [40]:
!tree MyAnimeList-Database-master/

Folder PATH listing
Volume serial number is 70E2-63CA
C:\USERS\HP\DESKTOP\DSA_INTERVIEW\BLIND75\DSA-WITH-PYTHON\MYANIMELIST-DATABASE-MASTER
+---data
    +---html

### Loading and Checking Data

In [41]:
anime_data = pd.read_csv('MyAnimeList-Database-master/data/anime.csv')
anime_list = pd.read_csv('MyAnimeList-Database-master/data/animelist.csv')
anime_synop = pd.read_csv('MyAnimeList-Database-master/data/anime_with_synopsis.csv')

In [42]:
anime_data.columns

Index(['MAL_ID', 'Name', 'Score', 'Genres', 'English name', 'Japanese name',
       'Type', 'Episodes', 'Aired', 'Premiered', 'Producers', 'Licensors',
       'Studios', 'Source', 'Duration', 'Rating', 'Ranked', 'Popularity',
       'Members', 'Favorites', 'Watching', 'Completed', 'On-Hold', 'Dropped',
       'Plan to Watch', 'Score-10', 'Score-9', 'Score-8', 'Score-7', 'Score-6',
       'Score-5', 'Score-4', 'Score-3', 'Score-2', 'Score-1'],
      dtype='object')

In [43]:
anime_data.shape

(17562, 35)

In [44]:
anime_data.head()

,MAL_ID,Name,Score,Genres,English name,Japanese name,Type,Episodes,Aired,Premiered,Producers,Licensors,Studios,Source,Duration,Rating,Ranked,Popularity,Members,Favorites,Watching,Completed,On-Hold,Dropped,Plan to Watch,Score-10,Score-9,Score-8,Score-7,Score-6,Score-5,Score-4,Score-3,Score-2,Score-1
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",Cowboy Bebop,カウボーイビバップ,TV,26,"Apr 3, 1998 to Apr 24, 1999",Spring 1998,Bandai Visual,"Funimation, Bandai Entertainment",Sunrise,Original,24 min. per ep.,R - 17+ (violence & profanity),28.0,39,1251960,61971,105808,718161,71513,26678,329800,229170.0,182126.0,131625.0,62330.0,20688.0,8904.0,3184.0,1357.0,741.0,1580.0
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",Cowboy Bebop:The Movie,カウボーイビバップ 天国の扉,Movie,1,"Sep 1, 2001",Unknown,"Sunrise, Bandai Visual",Sony Pictures Entertainment,Bones,Original,1 hr. 55 min.,R - 17+ (violence & profanity),159.0,518,273145,1174,4143,208333,1935,770,57964,30043.0,49201.0,49505.0,22632.0,5805.0,1877.0,577.0,221.0,109.0,379.0
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",Trigun,トライガン,TV,26,"Apr 1, 1998 to Sep 30, 1998",Spring 1998,Victor Entertainment,"Funimation, Geneon Entertainment USA",Madhouse,Manga,24 min. per ep.,PG-13 - Teens 13 or older,266.0,201,558913,12944,29113,343492,25465,13925,146918,50229.0,75651.0,86142.0,49432.0,15376.0,5838.0,1965.0,664.0,316.0,533.0
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",Witch Hunter Robin,Witch Hunter ROBIN (ウイッチハンターロビン),TV,26,"Jul 2, 2002 to Dec 24, 2002",Summer 2002,"TV Tokyo, Bandai Visual, Dentsu, Victor Entert...","Funimation, Bandai Entertainment",Sunrise,Original,25 min. per ep.,PG-13 - Teens 13 or older,2481.0,1467,94683,587,4300,46165,5121,5378,33719,2182.0,4806.0,10128.0,11618.0,5709.0,2920.0,1083.0,353.0,164.0,131.0
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",Beet the Vandel Buster,冒険王ビィト,TV,52,"Sep 30, 2004 to Sep 29, 2005",Fall 2004,"TV Tokyo, Dentsu",Unknown,Toei Animation,Manga,23 min. per ep.,PG - Children,3710.0,4369,13224,18,642,7314,766,1108,3394,312.0,529.0,1242.0,1713.0,1068.0,634.0,265.0,83.0,50.0,27.0

In [51]:
#checking basic statistics
anime_data.describe()

,MAL_ID,Popularity,Members,Favorites,Watching,Completed,On-Hold,Dropped,Plan to Watch
count,17562.000000,17562.000000,1.756200e+04,17562.000000,17562.000000,1.756200e+04,17562.000000,17562.000000,17562.000000
mean,21477.192347,8763.452340,3.465854e+04,457.746270,2231.487758,2.209557e+04,955.049653,1176.599533,8199.831227
std,14900.093170,5059.327278,1.252821e+05,4063.473313,14046.688133,9.100919e+04,4275.675096,4740.348653,23777.691963
min,1.000000,0.000000,1.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,1.000000
25%,5953.500000,4383.500000,3.360000e+02,0.000000,13.000000,1.110000e+02,6.000000,37.000000,112.000000
50%,22820.000000,8762.500000,2.065000e+03,3.000000,73.000000,8.175000e+02,45.000000,77.000000,752.500000
75%,35624.750000,13145.000000,1.322325e+04,31.000000,522.000000,6.478000e+03,291.750000,271.000000,4135.500000
max,48492.000000,17565.000000,2.589552e+06,183914.000000,887333.000000,2.182587e+06,187919.000000,174710.000000,425531.000000

In [52]:
anime_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17562 entries, 0 to 17561
Data columns (total 35 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MAL_ID         17562 non-null  int64
 1   Name           17562 non-null  object
 2   Score          17562 non-null  object
 3   Genres         17562 non-null  object
 4   English name   17562 non-null  object
 5   Japanese name  17562 non-null  object
 6   Type           17562 non-null  object
 7   Episodes       17562 non-null  object
 8   Aired          17562 non-null  object
 9   Premiered      17562 non-null  object
 10  Producers      17562 non-null  object
 11  Licensors      17562 non-null  object
 12  Studios        17562 non-null  object
 13  Source         17562 non-null  object
 14  Duration       17562 non-null  object
 15  Rating         17562 non-null  object
 16  Ranked         17562 non-null  object
 17  Popularity     17562 non-null  int64
 18  Members        17562 non-null  int64
 19  Favorites      17562 non-null  int64
 20  Watching       17562 non-null  int64
 21  Completed      17562 non-null  int64
 22  On-Hold        17562 non-null  int64
 23  Dropped        17562 non-null  int64
 24  Plan to Watch  17562 non-null  int64
 25  Score-10       17562 non-null  object
 26  Score-9        17562 non-null  object
 27  Score-8        17562 non-null  object
 28  Score-7        17562 non-null  object
 29  Score-6        17562 non-null  object
 30  Score-5        17562 non-null  object
 31  Score-4        17562 non-null  object
 32  Score-3        17562 non-null  object
 33  Score-2        17562 non-null  object
 34  Score-1        17562 non-null  object
dtypes: int64(9), object(26)
memory usage: 4.7+ MB

In [59]:
anime_data.isnull()

,MAL_ID,Name,Score,Genres,English name,Japanese name,Type,Episodes,Aired,Premiered,Producers,Licensors,Studios,Source,Duration,Rating,Ranked,Popularity,Members,Favorites,Watching,Completed,On-Hold,Dropped,Plan to Watch,Score-10,Score-9,Score-8,Score-7,Score-6,Score-5,Score-4,Score-3,Score-2,Score-1
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17557,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
17558,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
17559,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
17560,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
17561,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [60]:
anime_data.count()

MAL_ID          17562
Name            17562
Score           17562
Genres          17562
English name    17562
                ...
Score-5         17562
Score-4         17562
Score-3         17562
Score-2         17562
Score-1         17562
Length: 35, dtype: int64

In [62]:
anime_data.head().T

,0,1,2,3,4
MAL_ID,1,5,6,7,8
Name,Cowboy Bebop,Cowboy Bebop: Tengoku no Tobira,Trigun,Witch Hunter Robin,Bouken Ou Beet
Score,8.78,8.39,8.24,7.27,6.98
Genres,"Action, Adventure, Comedy, Drama, Sci-Fi, Space","Action, Drama, Mystery, Sci-Fi, Space","Action, Sci-Fi, Adventure, Comedy, Drama, Shounen","Action, Mystery, Police, Supernatural, Drama, ...","Adventure, Fantasy, Shounen, Supernatural"
English name,Cowboy Bebop,Cowboy Bebop:The Movie,Trigun,Witch Hunter Robin,Beet the Vandel Buster
...,...,...,...,...,...
Score-5,8904.0,1877.0,5838.0,2920.0,634.0
Score-4,3184.0,577.0,1965.0,1083.0,265.0
Score-3,1357.0,221.0,664.0,353.0,83.0
Score-2,741.0,109.0,316.0,164.0,50.0
Score-1,1580.0,379.0,533.0,131.0,27.0

In [63]:
anime_data.columns

Index(['MAL_ID', 'Name', 'Score', 'Genres', 'English name', 'Japanese name',
       'Type', 'Episodes', 'Aired', 'Premiered', 'Producers', 'Licensors',
       'Studios', 'Source', 'Duration', 'Rating', 'Ranked', 'Popularity',
       'Members', 'Favorites', 'Watching', 'Completed', 'On-Hold', 'Dropped',
       'Plan to Watch', 'Score-10', 'Score-9', 'Score-8', 'Score-7', 'Score-6',
       'Score-5', 'Score-4', 'Score-3', 'Score-2', 'Score-1'],
      dtype='object')

In [64]:
anime_data["Score"]

0           8.78
1           8.39
2           8.24
3           7.27
4           6.98
          ...
17557    Unknown
17558    Unknown
17559    Unknown
17560    Unknown
17561    Unknown
Name: Score, Length: 17562, dtype: object

In [67]:
anime_data["Score"]

0           8.78
1           8.39
2           8.24
3           7.27
4           6.98
          ...
17557    Unknown
17558    Unknown
17559    Unknown
17560    Unknown
17561    Unknown
Name: Score, Length: 17562, dtype: object

In [68]:
anime_data.Score

0           8.78
1           8.39
2           8.24
3           7.27
4           6.98
          ...
17557    Unknown
17558    Unknown
17559    Unknown
17560    Unknown
17561    Unknown
Name: Score, Length: 17562, dtype: object

In [69]:
# Specify column names (if multiple)
anime_data[['Name', 'Score']]

                                  Name    Score
0                         Cowboy Bebop     8.78
1      Cowboy Bebop: Tengoku no Tobira     8.39
2                               Trigun     8.24
3                   Witch Hunter Robin     7.27
4                       Bouken Ou Beet     6.98
...                                ...      ...
17557  Daomu Biji Zhi Qinling Shen Shu  Unknown
17558                     Mieruko-chan  Unknown
17559  Higurashi no Naku Koro ni Sotsu  Unknown
17560      Yama no Susume: Next Summit  Unknown
17561                    Scarlet Nexus  Unknown

[17562 rows x 2 columns]

In [70]:
cols_to_use = [
    'MAL_ID', 'Name', 'Score', 'Genres', 'Type', 'Aired', 'Studios', 'Source'
]
anime_data_extracted = anime_data[cols_to_use]
anime_data_extracted.head()

,MAL_ID,Name,Score,Genres,Type,Aired,Studios,Source
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,"Apr 3, 1998 to Apr 24, 1999",Sunrise,Original
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",Movie,"Sep 1, 2001",Bones,Original
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",TV,"Apr 1, 1998 to Sep 30, 1998",Madhouse,Manga
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",TV,"Jul 2, 2002 to Dec 24, 2002",Sunrise,Original
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",TV,"Sep 30, 2004 to Sep 29, 2005",Toei Animation,Manga

In [71]:
# Specify row name
anime_data_extracted[0:3]

,MAL_ID,Name,Score,Genres,Type,Aired,Studios,Source
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,"Apr 3, 1998 to Apr 24, 1999",Sunrise,Original
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",Movie,"Sep 1, 2001",Bones,Original
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",TV,"Apr 1, 1998 to Sep 30, 1998",Madhouse,Manga

In [76]:
# Specify col name
anime_data_extracted[0:4]

,MAL_ID,Name,Score,Genres,Type,Aired,Studios,Source
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,"Apr 3, 1998 to Apr 24, 1999",Sunrise,Original
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",Movie,"Sep 1, 2001",Bones,Original
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",TV,"Apr 1, 1998 to Sep 30, 1998",Madhouse,Manga
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",TV,"Jul 2, 2002 to Dec 24, 2002",Sunrise,Original

In [77]:
anime_data_extracted.iloc[:, 0:4]

,MAL_ID,Name,Score,Genres
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space"
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space"
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen"
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ..."
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural"
...,...,...,...,...
17557,48481,Daomu Biji Zhi Qinling Shen Shu,Unknown,"Adventure, Mystery, Supernatural"
17558,48483,Mieruko-chan,Unknown,"Comedy, Horror, Supernatural"
17559,48488,Higurashi no Naku Koro ni Sotsu,Unknown,"Mystery, Dementia, Horror, Psychological, Supe..."
17560,48491,Yama no Susume: Next Summit,Unknown,"Adventure, Slice of Life, Comedy"
17561,48492,Scarlet Nexus,Unknown,"Action, Fantasy"

In [78]:
anime_data_extracted.iloc[0:4, 0:4]

,MAL_ID,Name,Score,Genres
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space"
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space"
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen"
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ..."

In [80]:
# Specify row name (if one)
anime_data_extracted.loc[0]

MAL_ID                                                   1
Name                                          Cowboy Bebop
Score                                                 8.78
Genres     Action, Adventure, Comedy, Drama, Sci-Fi, Space
Type                                                    TV
Aired                          Apr 3, 1998 to Apr 24, 1999
Studios                                            Sunrise
Source                                            Original
Name: 0, dtype: object

In [83]:
# Specify row names (if multiple)
anime_data_extracted.loc[3:8]

,MAL_ID,Name,Score,Genres,Type,Aired,Studios,Source
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",TV,"Jul 2, 2002 to Dec 24, 2002",Sunrise,Original
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",TV,"Sep 30, 2004 to Sep 29, 2005",Toei Animation,Manga
5,15,Eyeshield 21,7.95,"Action, Sports, Comedy, Shounen",TV,"Apr 6, 2005 to Mar 19, 2008",Gallop,Manga
6,16,Hachimitsu to Clover,8.06,"Comedy, Drama, Josei, Romance, Slice of Life",TV,"Apr 15, 2005 to Sep 27, 2005",J.C.Staff,Manga
7,17,Hungry Heart: Wild Striker,7.59,"Slice of Life, Comedy, Sports, Shounen",TV,"Sep 11, 2002 to Sep 10, 2003",Nippon Animation,Manga
8,18,Initial D Fourth Stage,8.15,"Action, Cars, Sports, Drama, Seinen",TV,"Apr 17, 2004 to Feb 18, 2006",A.C.G.T.,Manga

In [84]:
# Specify row names (if multiple)
anime_data_extracted.iloc[3:8]

,MAL_ID,Name,Score,Genres,Type,Aired,Studios,Source
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",TV,"Jul 2, 2002 to Dec 24, 2002",Sunrise,Original
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",TV,"Sep 30, 2004 to Sep 29, 2005",Toei Animation,Manga
5,15,Eyeshield 21,7.95,"Action, Sports, Comedy, Shounen",TV,"Apr 6, 2005 to Mar 19, 2008",Gallop,Manga
6,16,Hachimitsu to Clover,8.06,"Comedy, Drama, Josei, Romance, Slice of Life",TV,"Apr 15, 2005 to Sep 27, 2005",J.C.Staff,Manga
7,17,Hungry Heart: Wild Striker,7.59,"Slice of Life, Comedy, Sports, Shounen",TV,"Sep 11, 2002 to Sep 10, 2003",Nippon Animation,Manga

In [85]:
# Specify column name (if one)
anime_data_extracted.loc[:, 'Name']

0                           Cowboy Bebop
1        Cowboy Bebop: Tengoku no Tobira
2                                 Trigun
3                     Witch Hunter Robin
4                         Bouken Ou Beet
                      ...
17557    Daomu Biji Zhi Qinling Shen Shu
17558                       Mieruko-chan
17559    Higurashi no Naku Koro ni Sotsu
17560        Yama no Susume: Next Summit
17561                      Scarlet Nexus
Name: Name, Length: 17562, dtype: object

In [86]:
# Specify column names (if multiple)
anime_data_extracted.loc[:, ['MAL_ID', 'Name']]

       MAL_ID                             Name
0           1                     Cowboy Bebop
1           5  Cowboy Bebop: Tengoku no Tobira
2           6                           Trigun
3           7               Witch Hunter Robin
4           8                   Bouken Ou Beet
...       ...                              ...
17557   48481  Daomu Biji Zhi Qinling Shen Shu
17558   48483                     Mieruko-chan
17559   48488  Higurashi no Naku Koro ni Sotsu
17560   48491      Yama no Susume: Next Summit
17561   48492                    Scarlet Nexus

[17562 rows x 2 columns]

In [87]:
# Specify column names (if multiple)
anime_data_extracted.loc[0:6, ['MAL_ID', 'Name']]

   MAL_ID                             Name
0       1                     Cowboy Bebop
1       5  Cowboy Bebop: Tengoku no Tobira
2       6                           Trigun
3       7               Witch Hunter Robin
4       8                   Bouken Ou Beet
5      15                     Eyeshield 21
6      16             Hachimitsu to Clover

In [88]:
# Specify 3 rows from 0 and columns 'MAL_ID' and 'Name'
anime_data_extracted.loc[0:3, ['MAL_ID', 'Name']]

   MAL_ID                             Name
0       1                     Cowboy Bebop
1       5  Cowboy Bebop: Tengoku no Tobira
2       6                           Trigun
3       7               Witch Hunter Robin

In [89]:

anime_data_extracted.head()

,MAL_ID,Name,Score,Genres,Type,Aired,Studios,Source
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,"Apr 3, 1998 to Apr 24, 1999",Sunrise,Original
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",Movie,"Sep 1, 2001",Bones,Original
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",TV,"Apr 1, 1998 to Sep 30, 1998",Madhouse,Manga
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",TV,"Jul 2, 2002 to Dec 24, 2002",Sunrise,Original
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",TV,"Sep 30, 2004 to Sep 29, 2005",Toei Animation,Manga

In [90]:
# Get 'ID' of line 0
anime_data.at[0, 'Name']

'Cowboy Bebop'

In [92]:
df.shape

(5, 4)

In [91]:
df

    ID      City  Birth_year     Name
0  100     Tokyo        1990  Hiroshi
1  101     Osaka        1989    Akiko
2  102     Kyoto        1992     Yuki
3  103  Hokkaido        1997   Satoru
4  104     Tokyo        1982    Steve

In [93]:
# Creating new column
df['Score'] = np.arange(5) * 10
df

    ID      City  Birth_year     Name  Score
0  100     Tokyo        1990  Hiroshi      0
1  101     Osaka        1989    Akiko     10
2  102     Kyoto        1992     Yuki     20
3  103  Hokkaido        1997   Satoru     30
4  104     Tokyo        1982    Steve     40

In [94]:
df

    ID      City  Birth_year     Name  Score
0  100     Tokyo        1990  Hiroshi      0
1  101     Osaka        1989    Akiko     10
2  102     Kyoto        1992     Yuki     20
3  103  Hokkaido        1997   Satoru     30
4  104     Tokyo        1982    Steve     40

In [95]:
df.shape

(5, 5)

In [96]:
df.at[0, 'Birth_year'] = 2000
df

    ID      City  Birth_year     Name  Score
0  100     Tokyo        2000  Hiroshi      0
1  101     Osaka        1989    Akiko     10
2  102     Kyoto        1992     Yuki     20
3  103  Hokkaido        1997   Satoru     30
4  104     Tokyo        1982    Steve     40

In [97]:
print(anime_data_extracted['Score'] != 'Unknown')

0         True
1         True
2         True
3         True
4         True
         ...
17557    False
17558    False
17559    False
17560    False
17561    False
Name: Score, Length: 17562, dtype: bool

In [98]:
#　Condition filtering
anime_data_extracted = anime_data_extracted[anime_data_extracted['Score'] != 'Unknown']
anime_data_extracted.head()

,MAL_ID,Name,Score,Genres,Type,Aired,Studios,Source
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,"Apr 3, 1998 to Apr 24, 1999",Sunrise,Original
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",Movie,"Sep 1, 2001",Bones,Original
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",TV,"Apr 1, 1998 to Sep 30, 1998",Madhouse,Manga
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",TV,"Jul 2, 2002 to Dec 24, 2002",Sunrise,Original
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",TV,"Sep 30, 2004 to Sep 29, 2005",Toei Animation,Manga