# Cleaning Data using Pandas

- **3.1 Overview of Pandas**
    - 3.1.1 Loading Library

- **3.2 Date Structure of Pandas**
    - 3.2.1 Series Object
    - 3.2.2 DataFrame Object

- **3.3 Loading and Interacting with Data**
    - 3.3.1 Downloading Data from the Internet
    - 3.3.2 Data Loading and Checking Data

- **3.4 DataFrame Basics**
    - 3.4.1 Data Selection and Assignment
    - 3.4.2 Extracting Data with Specific Conditions
    - 3.4.3 Determination of nan (null)
    - 3.4.4 Sorting of Values
- **3.5 Merging and Concatenating Data**
    - 3.5.1 Merging Data
    - 3.5.2 Concatenating Data
- **3.6 Manipulating and Transforming Data**
    - 3.6.1 Deleting Data
    - 3.6.2 Removing Duplicates
    - 3.6.3 Mapping
    - 3.6.4 Bin Splitting
- **3.7 Aggregating Data**
- **3.8 Advanced: Hierarchical Grouping**
- **3.9 Advanced: Handling Missing or Anomalous Data**
    - 3.9.1 How to Handle Missing Data
    - 3.9.2 How to Handle Anomaly Data
- **3.10 Comprehensive Question**

In [149]:
import pandas as pd
import numpy as np
import numpy.random as random
from pandas import Series, DataFrame
import matplotlib.pyplot as plt

In [150]:
# Alphabetize the index
series_i = Series(
    [1, 1, 2, 3, 5, 8, 13],
    index=['a', 'b', 'c', 'd', 'e', 'f','g']
)

print(series_i)

a     1
b     1
c     2
d     3
e     5
f     8
g    13
dtype: int64

In [151]:
print('Element:', series_i.values)
print('index:', series_i.index)

Element: [ 1  1  2  3  5  8 13]
index: Index(['a', 'b', 'c', 'd', 'e', 'f', 'g'], dtype='object')

# DataFrame Objects

In [152]:
data = {
    'ID':['100', '101', '102', '103', '104'],
    'City':['Tokyo', 'Osaka', 'Kyoto', 'Hokkaido', 'Tokyo'],
    'Birth_year':[1990, 1989, 1992, 1997, 1982],
    'Name':['Hiroshi', 'Akiko', 'Yuki', 'Satoru', 'Steve']
}

df = DataFrame(data)

print(df)

    ID      City  Birth_year     Name
0  100     Tokyo        1990  Hiroshi
1  101     Osaka        1989    Akiko
2  102     Kyoto        1992     Yuki
3  103  Hokkaido        1997   Satoru
4  104     Tokyo        1982    Steve

In [153]:
df.columns

Index(['ID', 'City', 'Birth_year', 'Name'], dtype='object')

In [154]:
df["ID"]

0    100
1    101
2    102
3    103
4    104
Name: ID, dtype: object

In [12]:
df["City"]

0       Tokyo
1       Osaka
2       Kyoto
3    Hokkaido
4       Tokyo
Name: City, dtype: object

In [13]:
df.iloc[0:1]

    ID   City  Birth_year     Name
0  100  Tokyo        1990  Hiroshi

In [15]:
df.shape

(5, 4)

In [14]:
df.iloc[0:4]

    ID      City  Birth_year     Name
0  100     Tokyo        1990  Hiroshi
1  101     Osaka        1989    Akiko
2  102     Kyoto        1992     Yuki
3  103  Hokkaido        1997   Satoru

In [16]:
df.iloc[1:3,1:3]

    City  Birth_year
1  Osaka        1989
2  Kyoto        1992

In [17]:
df.head()

    ID      City  Birth_year     Name
0  100     Tokyo        1990  Hiroshi
1  101     Osaka        1989    Akiko
2  102     Kyoto        1992     Yuki
3  103  Hokkaido        1997   Satoru
4  104     Tokyo        1982    Steve

In [18]:
df_i = DataFrame(data, index=['a', 'b', 'c', 'd', 'e'])
print(df_i)

    ID      City  Birth_year     Name
a  100     Tokyo        1990  Hiroshi
b  101     Osaka        1989    Akiko
c  102     Kyoto        1992     Yuki
d  103  Hokkaido        1997   Satoru
e  104     Tokyo        1982    Steve

In [22]:
df_i.iloc[1:3,1:3]

    City  Birth_year
b  Osaka        1989
c  Kyoto        1992

In [26]:
df_i.iloc[1]

ID              101
City          Osaka
Birth_year     1989
Name          Akiko
Name: b, dtype: object

In [27]:
print('Element:', df_i.values)
print('Index:', df_i.index)
print('Column:', df_i.columns)

Element: [['100' 'Tokyo' 1990 'Hiroshi']
 ['101' 'Osaka' 1989 'Akiko']
 ['102' 'Kyoto' 1992 'Yuki']
 ['103' 'Hokkaido' 1997 'Satoru']
 ['104' 'Tokyo' 1982 'Steve']]
Index: Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
Column: Index(['ID', 'City', 'Birth_year', 'Name'], dtype='object')

In [32]:
df.describe() # concider only neumerical values

       Birth_year
count     5.00000
mean   1990.00000
std       5.43139
min    1982.00000
25%    1989.00000
50%    1990.00000
75%    1992.00000
max    1997.00000

In [33]:
df_i

    ID      City  Birth_year     Name
a  100     Tokyo        1990  Hiroshi
b  101     Osaka        1989    Akiko
c  102     Kyoto        1992     Yuki
d  103  Hokkaido        1997   Satoru
e  104     Tokyo        1982    Steve

In [155]:
#Specify the maximum number of columns to display
pd.set_option('display.max_columns', 50)
#Specify the maximum number of rows to display
pd.set_option('display.max_rows', 10)

# Dataset Description

In [156]:
# Libraries for retrieving data from the web and handling zip files
import requests, zipfile
from io import StringIO
import io

In [157]:
# Specify the url with data
url = 'https://github.com/Hernan4444/MyAnimeList-Database/archive/refs/heads/master.zip'

# Acquire data from the url
r = requests.get(url, stream=True)

# read and extract the zipfile
z = zipfile.ZipFile(io.BytesIO(r.content))
z.extractall()

In [158]:
# !sudo apt-get install tree

In [159]:
# !pip apt-get install tree

In [39]:
!pip install tree

Collecting tree
  Downloading Tree-0.2.4.tar.gz (6.5 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: Pillow in c:\users\hp\miniconda3\envs\pytorch\lib\site-packages (from tree) (12.0.0)
Collecting svgwrite (from tree)
  Downloading svgwrite-1.4.3-py3-none-any.whl.metadata (8.8 kB)
Requirement already satisfied: setuptools in c:\users\hp\miniconda3\envs\pytorch\lib\site-packages (from tree) (80.9.0)
Collecting click (from tree)
  Downloading click-8.5.0-py3-none-any.whl.metadata (2.6 kB)
Downloading click-8.5.0-py3-none-any.whl (125 kB)
Downloading svgwrite-1.4.3-py3-none-any.whl (67 kB)
Building wheels for collected packages: tree
  Building wheel for tree (pyproject.toml): started
  Building wheel for tree (pyproject.toml): finished with status 'done'
  Created wheel for tree: filename=tree-0.2.4-py3-none-any.whl size=7919 sha256=0e3b7265c8d372965dc363566fd4bb2d12a5f5da9746d5c247c6ec82639e7fb3
  Stored in directory: c:\users\hp\appdata\local\pip\cache\wheels\0d\b8\ca\bf432f4ef2a525e65b33da2bef014a06a0791cae6b448dc0e2
Successfully built tree
Installing collected packages: svgwrite, click, tree

   ------------- -------------------------- 1/3 [click]
   ---------------------------------------- 3/3 [tree]

Successfully installed click-8.5.0 svgwrite-1.4.3 tree-0.2.4

In [40]:
!tree MyAnimeList-Database-master/

Folder PATH listing
Volume serial number is 70E2-63CA
C:\USERS\HP\DESKTOP\DSA_INTERVIEW\BLIND75\DSA-WITH-PYTHON\MYANIMELIST-DATABASE-MASTER
+---data
    +---html

### Loading and Checking Data

In [160]:
anime_data = pd.read_csv('MyAnimeList-Database-master/data/anime.csv')
anime_list = pd.read_csv('MyAnimeList-Database-master/data/animelist.csv')
anime_synop = pd.read_csv('MyAnimeList-Database-master/data/anime_with_synopsis.csv')

In [161]:
anime_data.columns

Index(['MAL_ID', 'Name', 'Score', 'Genres', 'English name', 'Japanese name',
       'Type', 'Episodes', 'Aired', 'Premiered', 'Producers', 'Licensors',
       'Studios', 'Source', 'Duration', 'Rating', 'Ranked', 'Popularity',
       'Members', 'Favorites', 'Watching', 'Completed', 'On-Hold', 'Dropped',
       'Plan to Watch', 'Score-10', 'Score-9', 'Score-8', 'Score-7', 'Score-6',
       'Score-5', 'Score-4', 'Score-3', 'Score-2', 'Score-1'],
      dtype='object')

In [43]:
anime_data.shape

(17562, 35)

In [44]:
anime_data.head()

,MAL_ID,Name,Score,Genres,English name,Japanese name,Type,Episodes,Aired,Premiered,Producers,Licensors,Studios,Source,Duration,Rating,Ranked,Popularity,Members,Favorites,Watching,Completed,On-Hold,Dropped,Plan to Watch,Score-10,Score-9,Score-8,Score-7,Score-6,Score-5,Score-4,Score-3,Score-2,Score-1
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",Cowboy Bebop,カウボーイビバップ,TV,26,"Apr 3, 1998 to Apr 24, 1999",Spring 1998,Bandai Visual,"Funimation, Bandai Entertainment",Sunrise,Original,24 min. per ep.,R - 17+ (violence & profanity),28.0,39,1251960,61971,105808,718161,71513,26678,329800,229170.0,182126.0,131625.0,62330.0,20688.0,8904.0,3184.0,1357.0,741.0,1580.0
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",Cowboy Bebop:The Movie,カウボーイビバップ 天国の扉,Movie,1,"Sep 1, 2001",Unknown,"Sunrise, Bandai Visual",Sony Pictures Entertainment,Bones,Original,1 hr. 55 min.,R - 17+ (violence & profanity),159.0,518,273145,1174,4143,208333,1935,770,57964,30043.0,49201.0,49505.0,22632.0,5805.0,1877.0,577.0,221.0,109.0,379.0
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",Trigun,トライガン,TV,26,"Apr 1, 1998 to Sep 30, 1998",Spring 1998,Victor Entertainment,"Funimation, Geneon Entertainment USA",Madhouse,Manga,24 min. per ep.,PG-13 - Teens 13 or older,266.0,201,558913,12944,29113,343492,25465,13925,146918,50229.0,75651.0,86142.0,49432.0,15376.0,5838.0,1965.0,664.0,316.0,533.0
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",Witch Hunter Robin,Witch Hunter ROBIN (ウイッチハンターロビン),TV,26,"Jul 2, 2002 to Dec 24, 2002",Summer 2002,"TV Tokyo, Bandai Visual, Dentsu, Victor Entert...","Funimation, Bandai Entertainment",Sunrise,Original,25 min. per ep.,PG-13 - Teens 13 or older,2481.0,1467,94683,587,4300,46165,5121,5378,33719,2182.0,4806.0,10128.0,11618.0,5709.0,2920.0,1083.0,353.0,164.0,131.0
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",Beet the Vandel Buster,冒険王ビィト,TV,52,"Sep 30, 2004 to Sep 29, 2005",Fall 2004,"TV Tokyo, Dentsu",Unknown,Toei Animation,Manga,23 min. per ep.,PG - Children,3710.0,4369,13224,18,642,7314,766,1108,3394,312.0,529.0,1242.0,1713.0,1068.0,634.0,265.0,83.0,50.0,27.0

In [51]:
#checking basic statistics
anime_data.describe()

,MAL_ID,Popularity,Members,Favorites,Watching,Completed,On-Hold,Dropped,Plan to Watch
count,17562.000000,17562.000000,1.756200e+04,17562.000000,17562.000000,1.756200e+04,17562.000000,17562.000000,17562.000000
mean,21477.192347,8763.452340,3.465854e+04,457.746270,2231.487758,2.209557e+04,955.049653,1176.599533,8199.831227
std,14900.093170,5059.327278,1.252821e+05,4063.473313,14046.688133,9.100919e+04,4275.675096,4740.348653,23777.691963
min,1.000000,0.000000,1.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,1.000000
25%,5953.500000,4383.500000,3.360000e+02,0.000000,13.000000,1.110000e+02,6.000000,37.000000,112.000000
50%,22820.000000,8762.500000,2.065000e+03,3.000000,73.000000,8.175000e+02,45.000000,77.000000,752.500000
75%,35624.750000,13145.000000,1.322325e+04,31.000000,522.000000,6.478000e+03,291.750000,271.000000,4135.500000
max,48492.000000,17565.000000,2.589552e+06,183914.000000,887333.000000,2.182587e+06,187919.000000,174710.000000,425531.000000

In [52]:
anime_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17562 entries, 0 to 17561
Data columns (total 35 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MAL_ID         17562 non-null  int64
 1   Name           17562 non-null  object
 2   Score          17562 non-null  object
 3   Genres         17562 non-null  object
 4   English name   17562 non-null  object
 5   Japanese name  17562 non-null  object
 6   Type           17562 non-null  object
 7   Episodes       17562 non-null  object
 8   Aired          17562 non-null  object
 9   Premiered      17562 non-null  object
 10  Producers      17562 non-null  object
 11  Licensors      17562 non-null  object
 12  Studios        17562 non-null  object
 13  Source         17562 non-null  object
 14  Duration       17562 non-null  object
 15  Rating         17562 non-null  object
 16  Ranked         17562 non-null  object
 17  Popularity     17562 non-null  int64
 18  Members        17562 non-null  int64
 19  Favorites      17562 non-null  int64
 20  Watching       17562 non-null  int64
 21  Completed      17562 non-null  int64
 22  On-Hold        17562 non-null  int64
 23  Dropped        17562 non-null  int64
 24  Plan to Watch  17562 non-null  int64
 25  Score-10       17562 non-null  object
 26  Score-9        17562 non-null  object
 27  Score-8        17562 non-null  object
 28  Score-7        17562 non-null  object
 29  Score-6        17562 non-null  object
 30  Score-5        17562 non-null  object
 31  Score-4        17562 non-null  object
 32  Score-3        17562 non-null  object
 33  Score-2        17562 non-null  object
 34  Score-1        17562 non-null  object
dtypes: int64(9), object(26)
memory usage: 4.7+ MB

In [59]:
anime_data.isnull()

,MAL_ID,Name,Score,Genres,English name,Japanese name,Type,Episodes,Aired,Premiered,Producers,Licensors,Studios,Source,Duration,Rating,Ranked,Popularity,Members,Favorites,Watching,Completed,On-Hold,Dropped,Plan to Watch,Score-10,Score-9,Score-8,Score-7,Score-6,Score-5,Score-4,Score-3,Score-2,Score-1
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17557,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
17558,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
17559,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
17560,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
17561,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [60]:
anime_data.count()

MAL_ID          17562
Name            17562
Score           17562
Genres          17562
English name    17562
                ...
Score-5         17562
Score-4         17562
Score-3         17562
Score-2         17562
Score-1         17562
Length: 35, dtype: int64

In [62]:
anime_data.head().T

,0,1,2,3,4
MAL_ID,1,5,6,7,8
Name,Cowboy Bebop,Cowboy Bebop: Tengoku no Tobira,Trigun,Witch Hunter Robin,Bouken Ou Beet
Score,8.78,8.39,8.24,7.27,6.98
Genres,"Action, Adventure, Comedy, Drama, Sci-Fi, Space","Action, Drama, Mystery, Sci-Fi, Space","Action, Sci-Fi, Adventure, Comedy, Drama, Shounen","Action, Mystery, Police, Supernatural, Drama, ...","Adventure, Fantasy, Shounen, Supernatural"
English name,Cowboy Bebop,Cowboy Bebop:The Movie,Trigun,Witch Hunter Robin,Beet the Vandel Buster
...,...,...,...,...,...
Score-5,8904.0,1877.0,5838.0,2920.0,634.0
Score-4,3184.0,577.0,1965.0,1083.0,265.0
Score-3,1357.0,221.0,664.0,353.0,83.0
Score-2,741.0,109.0,316.0,164.0,50.0
Score-1,1580.0,379.0,533.0,131.0,27.0

In [63]:
anime_data.columns

Index(['MAL_ID', 'Name', 'Score', 'Genres', 'English name', 'Japanese name',
       'Type', 'Episodes', 'Aired', 'Premiered', 'Producers', 'Licensors',
       'Studios', 'Source', 'Duration', 'Rating', 'Ranked', 'Popularity',
       'Members', 'Favorites', 'Watching', 'Completed', 'On-Hold', 'Dropped',
       'Plan to Watch', 'Score-10', 'Score-9', 'Score-8', 'Score-7', 'Score-6',
       'Score-5', 'Score-4', 'Score-3', 'Score-2', 'Score-1'],
      dtype='object')

In [64]:
anime_data["Score"]

0           8.78
1           8.39
2           8.24
3           7.27
4           6.98
          ...
17557    Unknown
17558    Unknown
17559    Unknown
17560    Unknown
17561    Unknown
Name: Score, Length: 17562, dtype: object

In [67]:
anime_data["Score"]

0           8.78
1           8.39
2           8.24
3           7.27
4           6.98
          ...
17557    Unknown
17558    Unknown
17559    Unknown
17560    Unknown
17561    Unknown
Name: Score, Length: 17562, dtype: object

In [68]:
anime_data.Score

0           8.78
1           8.39
2           8.24
3           7.27
4           6.98
          ...
17557    Unknown
17558    Unknown
17559    Unknown
17560    Unknown
17561    Unknown
Name: Score, Length: 17562, dtype: object

In [69]:
# Specify column names (if multiple)
anime_data[['Name', 'Score']]

                                  Name    Score
0                         Cowboy Bebop     8.78
1      Cowboy Bebop: Tengoku no Tobira     8.39
2                               Trigun     8.24
3                   Witch Hunter Robin     7.27
4                       Bouken Ou Beet     6.98
...                                ...      ...
17557  Daomu Biji Zhi Qinling Shen Shu  Unknown
17558                     Mieruko-chan  Unknown
17559  Higurashi no Naku Koro ni Sotsu  Unknown
17560      Yama no Susume: Next Summit  Unknown
17561                    Scarlet Nexus  Unknown

[17562 rows x 2 columns]

In [70]:
cols_to_use = [
    'MAL_ID', 'Name', 'Score', 'Genres', 'Type', 'Aired', 'Studios', 'Source'
]
anime_data_extracted = anime_data[cols_to_use]
anime_data_extracted.head()

,MAL_ID,Name,Score,Genres,Type,Aired,Studios,Source
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,"Apr 3, 1998 to Apr 24, 1999",Sunrise,Original
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",Movie,"Sep 1, 2001",Bones,Original
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",TV,"Apr 1, 1998 to Sep 30, 1998",Madhouse,Manga
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",TV,"Jul 2, 2002 to Dec 24, 2002",Sunrise,Original
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",TV,"Sep 30, 2004 to Sep 29, 2005",Toei Animation,Manga

In [71]:
# Specify row name
anime_data_extracted[0:3]

,MAL_ID,Name,Score,Genres,Type,Aired,Studios,Source
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,"Apr 3, 1998 to Apr 24, 1999",Sunrise,Original
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",Movie,"Sep 1, 2001",Bones,Original
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",TV,"Apr 1, 1998 to Sep 30, 1998",Madhouse,Manga

In [76]:
# Specify col name
anime_data_extracted[0:4]

,MAL_ID,Name,Score,Genres,Type,Aired,Studios,Source
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,"Apr 3, 1998 to Apr 24, 1999",Sunrise,Original
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",Movie,"Sep 1, 2001",Bones,Original
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",TV,"Apr 1, 1998 to Sep 30, 1998",Madhouse,Manga
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",TV,"Jul 2, 2002 to Dec 24, 2002",Sunrise,Original

In [77]:
anime_data_extracted.iloc[:, 0:4]

,MAL_ID,Name,Score,Genres
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space"
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space"
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen"
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ..."
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural"
...,...,...,...,...
17557,48481,Daomu Biji Zhi Qinling Shen Shu,Unknown,"Adventure, Mystery, Supernatural"
17558,48483,Mieruko-chan,Unknown,"Comedy, Horror, Supernatural"
17559,48488,Higurashi no Naku Koro ni Sotsu,Unknown,"Mystery, Dementia, Horror, Psychological, Supe..."
17560,48491,Yama no Susume: Next Summit,Unknown,"Adventure, Slice of Life, Comedy"
17561,48492,Scarlet Nexus,Unknown,"Action, Fantasy"

In [78]:
anime_data_extracted.iloc[0:4, 0:4]

,MAL_ID,Name,Score,Genres
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space"
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space"
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen"
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ..."

In [80]:
# Specify row name (if one)
anime_data_extracted.loc[0]

MAL_ID                                                   1
Name                                          Cowboy Bebop
Score                                                 8.78
Genres     Action, Adventure, Comedy, Drama, Sci-Fi, Space
Type                                                    TV
Aired                          Apr 3, 1998 to Apr 24, 1999
Studios                                            Sunrise
Source                                            Original
Name: 0, dtype: object

In [83]:
# Specify row names (if multiple)
anime_data_extracted.loc[3:8]

,MAL_ID,Name,Score,Genres,Type,Aired,Studios,Source
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",TV,"Jul 2, 2002 to Dec 24, 2002",Sunrise,Original
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",TV,"Sep 30, 2004 to Sep 29, 2005",Toei Animation,Manga
5,15,Eyeshield 21,7.95,"Action, Sports, Comedy, Shounen",TV,"Apr 6, 2005 to Mar 19, 2008",Gallop,Manga
6,16,Hachimitsu to Clover,8.06,"Comedy, Drama, Josei, Romance, Slice of Life",TV,"Apr 15, 2005 to Sep 27, 2005",J.C.Staff,Manga
7,17,Hungry Heart: Wild Striker,7.59,"Slice of Life, Comedy, Sports, Shounen",TV,"Sep 11, 2002 to Sep 10, 2003",Nippon Animation,Manga
8,18,Initial D Fourth Stage,8.15,"Action, Cars, Sports, Drama, Seinen",TV,"Apr 17, 2004 to Feb 18, 2006",A.C.G.T.,Manga

In [84]:
# Specify row names (if multiple)
anime_data_extracted.iloc[3:8]

,MAL_ID,Name,Score,Genres,Type,Aired,Studios,Source
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",TV,"Jul 2, 2002 to Dec 24, 2002",Sunrise,Original
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",TV,"Sep 30, 2004 to Sep 29, 2005",Toei Animation,Manga
5,15,Eyeshield 21,7.95,"Action, Sports, Comedy, Shounen",TV,"Apr 6, 2005 to Mar 19, 2008",Gallop,Manga
6,16,Hachimitsu to Clover,8.06,"Comedy, Drama, Josei, Romance, Slice of Life",TV,"Apr 15, 2005 to Sep 27, 2005",J.C.Staff,Manga
7,17,Hungry Heart: Wild Striker,7.59,"Slice of Life, Comedy, Sports, Shounen",TV,"Sep 11, 2002 to Sep 10, 2003",Nippon Animation,Manga

In [85]:
# Specify column name (if one)
anime_data_extracted.loc[:, 'Name']

0                           Cowboy Bebop
1        Cowboy Bebop: Tengoku no Tobira
2                                 Trigun
3                     Witch Hunter Robin
4                         Bouken Ou Beet
                      ...
17557    Daomu Biji Zhi Qinling Shen Shu
17558                       Mieruko-chan
17559    Higurashi no Naku Koro ni Sotsu
17560        Yama no Susume: Next Summit
17561                      Scarlet Nexus
Name: Name, Length: 17562, dtype: object

In [86]:
# Specify column names (if multiple)
anime_data_extracted.loc[:, ['MAL_ID', 'Name']]

       MAL_ID                             Name
0           1                     Cowboy Bebop
1           5  Cowboy Bebop: Tengoku no Tobira
2           6                           Trigun
3           7               Witch Hunter Robin
4           8                   Bouken Ou Beet
...       ...                              ...
17557   48481  Daomu Biji Zhi Qinling Shen Shu
17558   48483                     Mieruko-chan
17559   48488  Higurashi no Naku Koro ni Sotsu
17560   48491      Yama no Susume: Next Summit
17561   48492                    Scarlet Nexus

[17562 rows x 2 columns]

In [87]:
# Specify column names (if multiple)
anime_data_extracted.loc[0:6, ['MAL_ID', 'Name']]

   MAL_ID                             Name
0       1                     Cowboy Bebop
1       5  Cowboy Bebop: Tengoku no Tobira
2       6                           Trigun
3       7               Witch Hunter Robin
4       8                   Bouken Ou Beet
5      15                     Eyeshield 21
6      16             Hachimitsu to Clover

In [88]:
# Specify 3 rows from 0 and columns 'MAL_ID' and 'Name'
anime_data_extracted.loc[0:3, ['MAL_ID', 'Name']]

   MAL_ID                             Name
0       1                     Cowboy Bebop
1       5  Cowboy Bebop: Tengoku no Tobira
2       6                           Trigun
3       7               Witch Hunter Robin

In [89]:

anime_data_extracted.head()

,MAL_ID,Name,Score,Genres,Type,Aired,Studios,Source
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,"Apr 3, 1998 to Apr 24, 1999",Sunrise,Original
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",Movie,"Sep 1, 2001",Bones,Original
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",TV,"Apr 1, 1998 to Sep 30, 1998",Madhouse,Manga
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",TV,"Jul 2, 2002 to Dec 24, 2002",Sunrise,Original
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",TV,"Sep 30, 2004 to Sep 29, 2005",Toei Animation,Manga

In [90]:
# Get 'ID' of line 0
anime_data.at[0, 'Name']

'Cowboy Bebop'

In [92]:
df.shape

(5, 4)

In [91]:
df

    ID      City  Birth_year     Name
0  100     Tokyo        1990  Hiroshi
1  101     Osaka        1989    Akiko
2  102     Kyoto        1992     Yuki
3  103  Hokkaido        1997   Satoru
4  104     Tokyo        1982    Steve

In [93]:
# Creating new column
df['Score'] = np.arange(5) * 10
df

    ID      City  Birth_year     Name  Score
0  100     Tokyo        1990  Hiroshi      0
1  101     Osaka        1989    Akiko     10
2  102     Kyoto        1992     Yuki     20
3  103  Hokkaido        1997   Satoru     30
4  104     Tokyo        1982    Steve     40

In [94]:
df

    ID      City  Birth_year     Name  Score
0  100     Tokyo        1990  Hiroshi      0
1  101     Osaka        1989    Akiko     10
2  102     Kyoto        1992     Yuki     20
3  103  Hokkaido        1997   Satoru     30
4  104     Tokyo        1982    Steve     40

In [95]:
df.shape

(5, 5)

In [96]:
df.at[0, 'Birth_year'] = 2000
df

    ID      City  Birth_year     Name  Score
0  100     Tokyo        2000  Hiroshi      0
1  101     Osaka        1989    Akiko     10
2  102     Kyoto        1992     Yuki     20
3  103  Hokkaido        1997   Satoru     30
4  104     Tokyo        1982    Steve     40

In [97]:
print(anime_data_extracted['Score'] != 'Unknown')

0         True
1         True
2         True
3         True
4         True
         ...
17557    False
17558    False
17559    False
17560    False
17561    False
Name: Score, Length: 17562, dtype: bool

In [98]:
#　Condition filtering
anime_data_extracted = anime_data_extracted[anime_data_extracted['Score'] != 'Unknown']
anime_data_extracted.head()

,MAL_ID,Name,Score,Genres,Type,Aired,Studios,Source
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,"Apr 3, 1998 to Apr 24, 1999",Sunrise,Original
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",Movie,"Sep 1, 2001",Bones,Original
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",TV,"Apr 1, 1998 to Sep 30, 1998",Madhouse,Manga
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",TV,"Jul 2, 2002 to Dec 24, 2002",Sunrise,Original
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",TV,"Sep 30, 2004 to Sep 29, 2005",Toei Animation,Manga

In [99]:
#　Condition filtering
anime_data_extracted = anime_data_extracted[anime_data_extracted['Score'] != 'Unknown']
anime_data_extracted.head()

,MAL_ID,Name,Score,Genres,Type,Aired,Studios,Source
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,"Apr 3, 1998 to Apr 24, 1999",Sunrise,Original
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",Movie,"Sep 1, 2001",Bones,Original
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",TV,"Apr 1, 1998 to Sep 30, 1998",Madhouse,Manga
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",TV,"Jul 2, 2002 to Dec 24, 2002",Sunrise,Original
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",TV,"Sep 30, 2004 to Sep 29, 2005",Toei Animation,Manga

In [100]:
# 'Studios' is Nomad or Sunrise
anime_data_extracted[(anime_data_extracted['Studios'] == 'Nomad') | (anime_data_extracted['Studios'] == 'Sunrise')].head()

,MAL_ID,Name,Score,Genres,Type,Aired,Studios,Source
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,"Apr 3, 1998 to Apr 24, 1999",Sunrise,Original
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",TV,"Jul 2, 2002 to Dec 24, 2002",Sunrise,Original
18,28,Yakitate!! Japan,7.95,"Comedy, Shounen",TV,"Oct 12, 2004 to Mar 14, 2006",Sunrise,Manga
45,64,Rozen Maiden,7.44,"Action, Comedy, Drama, Magic, Seinen",TV,"Oct 8, 2004 to Dec 24, 2004",Nomad,Manga
46,65,Rozen Maiden: Träumend,7.65,"Action, Comedy, Drama, Magic, Seinen",TV,"Oct 21, 2005 to Jan 27, 2006",Nomad,Manga

In [110]:
anime_data_extracted["Studios"].unique()

array(['Sunrise', 'Bones', 'Madhouse', 'Toei Animation', 'Gallop',
       'J.C.Staff', 'Nippon Animation', 'A.C.G.T.', 'Studio Pierrot',
       'Trans Arts', 'Studio Comet', 'Gonzo', 'Studio Deen',
       'Gainax, Tatsunoko Production', 'Gainax, Production I.G', 'OLM',
       'Production I.G', 'Gallop, Studio Deen', 'Tokyo Movie Shinsha',
       'Bee Train', 'AIC', 'Hal Film Maker', 'Digital Frontier',
       'Bee Train, Xebec', 'Xebec', 'feel., Zexcs', 'Daume', 'Nomad',
       'Kyoto Animation', 'Group TAC', 'Seven Arcs', 'Asread',
       'Sunrise, Studio Hibari', 'Sunrise, Studio Deen',
       'Sunrise, Nakamura Production', 'TMS Entertainment',
       'Imagin, Studio Live', 'Zexcs', 'Telecom Animation Film',
       'ufotable, feel., Studio Flag', 'Studio Matrix', 'feel.', 'TNK',
       'Gainax, J.C.Staff', 'Gainax, Shaft', 'Studio Fantasia',
       'Gainax, Toei Animation', 'Studio Ghibli', 'Production Reed',
       'Gallop, Studio Comet', 'Pastel', 'Unknown', 'Satelight',
       'Madhouse, Imagin', 'Arms', 'Manglobe', 'APPP', 'ufotable',
       'Chaos Project, GANSIS', 'Tokyo Kids', 'Palm Studio',
       'AIC Spirits', 'Yumeta Company', 'Shin-Ei Animation',
       'CoMix Wave Films', 'Studio Hibari', 'Silver', 'Radix',
       'Magic Bus', 'Gainax, Madhouse', 'Tatsunoko Production', 'Ajia-Do',
       'Madhouse, Tokyo Movie Shinsha', 'Annapuru', 'Triangle Staff',
       'Square Enix', 'TNK, Production Reed',
       'Studio Fantasia, Amber Film Works', 'Gainax', 'E&G Films',
       'Shaft', 'Trinet Entertainment, Picture Magic', 'AIC ASTA',
       'Hal Film Maker, Nomad', 'M.S.C', 'Picture Magic, Rikuentai',
       'TMS Entertainment, Tokyo Kids, Minami Machi Bugyousho',
       'Milky Animation Label', 'Studio Fantasia, animate Film',
       'Actas, Production Reed', 'Actas', 'Chaos Project',
       'Group TAC, Japan Vistec', 'Bones, Sunrise', 'WAO World',
       'G&G Entertainment', 'Studio 4°C', 'Gonzo, Production I.G',
       'Ashi Production', 'Arcs Create', 'animate Film',
       'Production I.G, Xebec', 'Plum, Magic Bus',
       'Kyoto Animation, Sunrise', 'Artland', 'Karaku',
       'Satelight, Production Reed', "Brain's Base", 'Eiken', 'Plum',
       'Trinet Entertainment', 'Actas, SynergySP', 'OLM, Production Reed',
       'Madhouse, Studio Deen', 'Studio 4°C, Sunrise', 'Topcraft',
       'Studio Junio', 'Radix, Marine Entertainment',
       'Kyoto Animation, Tatsunoko Production',
       'Studio Deen, Studio Hibari, Production Reed',
       'Madhouse, Production Reed', 'KSS', 'Madhouse, feel.',
       'Studio Flag', 'Pink Pineapple', 'Zero-G Room', 'OLM, AIC ASTA',
       'Radix, Chaos Project', 'Madhouse, Telecom Animation Film',
       'Shogakukan Music & Digital Entertainment', 'SynergySP',
       'J.C.Staff, Studio Ghibli', 'Group TAC, View Works',
       'Studio Rikka', 'Madhouse, Satelight, Graphinica',
       'Creators Dot Com', 'Group TAC, Ginga Ya', 'Tezuka Productions',
       'Xebec, Production Reed', 'Group TAC, Animaruya',
       'Studio Pierrot, Arms', 'Vega Entertainment', 'Artland, Magic Bus',
       'Y.O.U.C', 'Shinkuukan', 'Planet', 'Studio Live',
       'Triangle Staff, Studio Wombat', 'Picture Magic',
       'Studio Hibari, Production Reed', 'OLM Digital',
       'AIC Spirits, Group TAC', 'AIC, Artmic', 'Diomedéa', 'Remic',
       'Madhouse, TNK', 'Enoki Films, Dai Nippon Printing', 'Studio Jam',
       'Gonzo, Satelight', 'Phoenix Entertainment',
       'Group TAC, G&G Entertainment', 'T.P.O', 'Mook Animation',
       'Toei Animation, Production Reed',
       'Production I.G, Production Reed', 'Studio Deen, Kitty Films',
       'Gainax, Studio Deen', 'Triangle Staff, animate Film', 'AIC, APPP',
       'Group TAC, Amuse', 'Oh! Production',
       'Gallop, Group TAC, Studio Junio', 'View Works',
       'Sunrise, Toei Animation', 'Doga Kobo',
       'Artland, Tatsunoko Production', 'Production I.G, Studio Deen',
       'Romanov Films', 'Kaname Productions, Idol', 'Agent 21',
       'Studio Egg', 'Yamato Works',
       'Trinet Entertainment, Studio Hibari', 'ACC Production',
       'Tamura Shigeru Studio', 'Mushi Production', 'Studio Signal',
       'Bee Media', 'Gainax, Group TAC', 'AIC, animate Film',
       'Toei Animation, Studio World', 'Studio Pierrot, Studio Deen',
       'The Answer Studio', 'Madhouse, Studio 4°C',
       'J.C.Staff, Production Reed',
       'Production Reed, D.A.S.T., Studio 88', 'Studio 88',
       'AIC, Artmic, Darts', 'Darts', 'D.A.S.T.', 'Azeta Pictures',
       'AT-2', 'Imagin', 'Studio Junio, Annapuru',
       'Sunrise, Production Reed', 'Artmic', 'Gonzo, AIC',
       'Group TAC, Studio Junio', 'Studio Pierrot, AIC ASTA',
       'Ishimori Entertainment', 'JCF', 'Madhouse, Group TAC',
       'Asahi Production', 'Shaft, TNK', 'Office Take Off',
       'Sugar Boy, Blue Cat', 'Venet', 'Dynamic Planning',
       'Studio Z5, Studio March', 'Academy Productions',
       "Shaft, Brain's Base, Japan Vistec", 'Rikuentai', 'Echo',
       'Ginga Ya', 'Kitty Films',
       'Tokyo Movie Shinsha, Filmlink International',
       'Filmlink International', 'J.C.Staff, animate Film',
       'Genco, Radix', 'T-Rex', 'Studio G-1Neo',
       'Studio Pierrot, Ajia-Do', 'Front Line', 'RAMS', 'Public & Basic',
       'Anime R, Aubec', 'AIC Spirits, BeSTACK', 'Kaname Productions',
       'Gonzo, Palm Studio', 'Xebec, Group TAC', 'Image House',
       'J.C.Staff, Life Work', 'Madhouse, Studio Deen, Magic Bus',
       'Ishikawa Pro', 'Artland, AIC, Artmic', 'Mook DLE', 'Pierrot Plus',
       'Gallop, TMS Entertainment', 'Ajia-Do, Studio Deen',
       'Studio Kelmadick', 'Sanrio', 'Aubec', 'Gainax, Studio 4°C',
       'Big Bang', 'AIC, Artmic, animate Film', 'AIC, Studio Kyuuma',
       'Studio OX', 'Eiken, Magic Bus', 'AIC, Studio Hakk',
       'Tsuchida Productions', 'P.A. Works', 'Himajin Planning',
       'Soeishinsha', 'Lilix', 'Telescreen',
       'Tokyo Kids, Minami Machi Bugyousho', 'A-1 Pictures', 'PPM',
       'Gonzo, Asread', 'Youmex', 'Rikuentai, Nikkatsu',
       'Sunrise, Sanrio', 'Nippon Animation, Shaft', 'Animation 21',
       'AIC, Darts', 'Visual 80', 'Urban Product',
       'Front Line, Studio G-1Neo', 'Studio Comet, Studio Sign',
       'Flavors Soft', 'Studio Core', 'Studio 9 MAiami', 'Arcturus',
       'Studio Wombat', 'Trinet Entertainment, Studio Kyuuma',
       'Studio Fantasia, Chaos Project', 'Bee Media, Studio Signal',
       'Triple X', 'Madhouse, TMS Entertainment',
       'Bee Train, Cookie Jar Entertainment', 'Madhouse, Toei Animation',
       'Production I.G, Tatsunoko Production', 'Genco, Triangle Staff',
       'Xebec, Genco, Triangle Staff', 'Animation Staff Room', 'Oxybot',
       'Tatsunoko Production, Tama Production', 'Sunwoo Entertainment',
       'Khara', 'Shochiku Animation Institute',
       'Studio Kyuuma, Studio Kikan, Azeta Pictures',
       'Madhouse, Studio Fantasia', 'Tezuka Productions, Toho',
       'Production Reed, Asahi Production',
       'Tatsunoko Production, Production Reed, Asahi Production',
       'Panmedia, Meruhensha',
       'Gonzo, Gainax, Production I.G, Madhouse, Studio 4°C, Satelight, CoMix Wave Films',
       'Japan Taps', 'Studio Bogey', 'Tama Production',
       'Madhouse, Tezuka Productions',
       'Telecom Animation Film, Shirogumi', 'Artland, Madhouse',
       'Piko Studio', 'Think Corporation', 'Studio Unicorn, Hiro Media',
       'Studio Zero, Tokyo Movie', 'Dongwoo A&E', 'Kazuki Production',
       'PrimeTime', 'CyberConnect2', 'Eiken, Studio Live', 'Anpro',
       'J.C.Staff, Tatsunoko Production', 'Anime Antenna Iinkai',
       'Nippon Animation, Production Reed', 'White Fox', 'Shirogumi',
       "Actas, Brain's Base", 'Arms, Studio Kikan', 'Studio Sign',
       'Tatsunoko Production, Studio World',
       'Bones, Telecom Animation Film', 'Blue Cat',
       'J.C.Staff, Production I.G', 'Kanaban Graphics', 'Suzuki Mirano',
       'Kokusai Eigasha', 'Studio Zero', 'Nippon Animation, Xebec',
       'GEN Productions', 'DAX Production',
       'Dai-Ichi Douga, Dongyang Animation', 'OLM, Pastel',
       'Studio Eromatick', 'Knack Productions', 'A-1 Pictures, Ordet',
       'Production I.G, Trans Arts', 'Anime R',
       'Nippon Animation, SynergySP, Shirogumi', 'Bones, Sanrio',
       'Dai-Ichi Douga',
       'Bee Train, Production I.G, Madhouse, Studio 4°C',
       'Xebec, Kanaban Graphics', 'Studio Comet, KeyEast, REALTHING',
       'Sunrise, Kino Production', 'Madhouse, Animation Staff Room',
       'Bones, Kinema Citrus', 'Oz', 'Jinnis Animation Studios',
       'Green Bunny', 'Gainax, feel.', 'Office Takeout',
       'Studio Ghibli, Ajia-Do', 'AIC Spirits, Asread', 'DLE',
       'Nippon Ramayana Film Co.', 'Madhouse, Tatsunoko Production',
       'Tele-Cartoon Japan', 'animate Film, Studio Kikan',
       'Minami Machi Bugyousho', 'AIC, Magic Bus, Ashi Production',
       'AIC PLUS+', 'Studio Nue', 'Ajia-Do, Group TAC',
       'Gainax, Magic Bus', 'TMS Entertainment, Tezuka Productions',
       'Satelight, 8bit', "Brain's Base, Marvy Jack", 'Egg',
       'Bee Media, Code', 'AIC Spirits, Digital Frontier', 'Studio Kikan',
       'Milky Animation Label, Studio Jam', 'Office AO',
       'Marza Animation Planet', 'David Production',
       'Gonzo, Picture Magic', 'SILVER LINK.',
       'Studio Hibari, Grouper Productions',
       'Kyoto Animation, Production I.G, Shin-Ei Animation',
       'Grouper Productions, Animation Staff Room', 'Ripple Film',
       'Heewon Entertainment, NHK Enterprises',
       'Tatsunoko Production, SynergySP, Seven', 'Kinema Citrus',
       'Production I.G, Polygon Pictures', 'Milky Cartoon',
       'Production I.G, animate Film', 'animate Film, Visual 80',
       'Picograph', 'OLM, P.A. Works', 'GoHands', 'Toei Video', 'Anima',
       'Artmic, animate Film', 'Hoods Entertainment', 'Natural High',
       'Studio Pierrot, Studio Hibari', 'Studio Deen, DAX Production',
       'Schoolzone', 'Kachidoki Studio', 'PoRO',
       'Satelight, A-1 Pictures', 'Studio Take Off', 'Fanworks',
       'Studio Blanc', 'Studio Coa', 'Shanghai Animation Film Studio',
       'Bones, Production I.G, Studio 4°C, Toei Animation',
       'Encourage Films',
       'Future Planet, Beijing Huihuang Animation Company', 'Indeprox',
       'TYO Animations', 'Robot Communications', 'Ordet', 'Kate Arrow',
       'Studio Korumi', 'Asahi Production, Shochiku Animation Institute',
       'Stingray', 'Arms, TNK', 'Gathering',
       'Panda Factory, Studio PuYUKAI', 'G-Lam', 'Bridge', 'dwarf',
       'ChuChu', 'Hal Film Maker, TYO Animations', 'Daewon Media',
       'Bee Media, 81 Produce', 'Sunrise, Telecom Animation Film',
       'Sunrise, Ascension', 'Studio Crocodile', 'Studio World',
       'Panda Factory', 'Tatsunoko Production, SynergySP', 'AIC Classic',
       'Animaruya', 'Tohokushinsha Film Corporation', 'TAKI Corporation',
       'Studio Bogey, Public & Basic', 'AIC Build', 'Rising Force',
       'Studio Gokumi', 'Tokyo Media Connections', 'Studio Unicorn',
       'Public & Basic, Ripple Film', 'Primastea', '8bit',
       'Studio Pierrot, Pierrot Plus', 'ElectromagneticWave',
       'Studio Meditation With a Pencil', 'AIC Takarazuka',
       'Takahashi Studio, Suna Kouhou', 'Sunrise, Bandai Visual',
       'Kamikaze Douga', 'Project No.9', 'Studio PuYUKAI',
       'Production I.G, Welz Animation Studios', 'Seven',
       'A-1 Pictures, Bridge', 'Sparkly Key Animation Studio',
       'Studio Pierrot, David Production', 'Production I.G, Xebec, OLM',
       'Lerche', 'Ascension', 'Bones, Production Reed',
       'Toei Animation, Studio Nue', 'WAO World, MooGoo', 'B&T',
       'Digital Media Lab', 'Barnum Studio, Project No.9, Studio Blanc',
       'AIC, Remic', 'Production I.G, M.S.C',
       'Studio Fantasia, Rabbit Gate', 'Collaboration Works', 'Majin',
       'Satelight, ixtl', 'Graphinica', 'TNK, Kinema Citrus',
       'Ordet, SANZIGEN', 'J.C.Staff, Artland', 'Milky Cartoon, LMD',
       'Kenji Studio', 'Satelight, Encourage Films',
       'Production I.G, SANZIGEN', 'Gainax, Asahi Production', 'LMD',
       'Madhouse, Studio Gokumi', 'Xebec, AIC', 'J.C.Staff, Kitty Films',
       'C2C', 'RG Animation Studios', 'Marvy Jack', 'Gonzo, DLE',
       'Studio Chizu', 'SBS TV Production',
       'Studio Rikka, Purple Cow Studio Japan',
       'Tezuka Productions, MAPPA', 'Gonzo, LandQ studios',
       'Studio Pierrot, D.A.S.T.', 'Production IMS',
       'Tatsunoko Production, Dongwoo A&E', 'Odolttogi',
       'Sparky Animation', 'NHK', 'Hotline', 'Tomason',
       'Larx Entertainment', 'Production I.G, Studio 4°C, Shaft',
       'Shueisha', 'HS Pictures Studio', 'Anpro, teamKG', 'Trigger',
       'AIC Frontier', 'Sola Digital Arts', 'Gonzo, Hoods Entertainment',
       'Kazami Gakuen Koushiki Douga-bu', 'Passione',
       'Sunrise, Bandai Namco Pictures', 'MAPPA', 'Fifth Avenue',
       'SANZIGEN', 'Polygon Pictures, W+K Tokyo, Welz Animation Studios',
       'Ordet, LIDENFILMS', 'Mary Jane', 'Doga Kobo, Orange',
       'Hoods Entertainment, Production IMS', 'An DerCen',
       'Barnum Studio, Project No.9', 'Nippon Animation, Studio WHO',
       'J.C.Staff, Toei Animation', 'Nexus', 'Seven Arcs Pictures',
       'Charaction', 'Wit Studio', 'HOTZIPANG', 'Xebec, I.Gzwei',
       'LIDENFILMS', 'Bouncy', 'W+K Tokyo', 'Studio 4°C, Shirogumi',
       'Ordet, Encourage Films', 'feel., Assez Finaud Fabric',
       'Hoods Entertainment, Felix Film', 'Kaeruotoko Shokai', 'MooGoo',
       'SILVER LINK., Connect', 'Kyoto Animation, Animation Do',
       'Production I.G, Madhouse', 'Hoods Entertainment, teamKG',
       'Tatsunoko Production, Ordet', 'Xebec, OLM', 'Mirai Film', 'ILCA',
       'Studio Moriken', 'Studio 1st', 'SANZIGEN, LIDENFILMS',
       'Madhouse, MAPPA', 'Polygon Pictures', 'Yaoyorozu', 'Opera House',
       'Studio Pierrot, Kyoto Animation', 'Studio Colorido', 'NAZ',
       'Minakata Laboratory', 'Kinema Citrus, Orange',
       'Production I.G, Zexcs', 'C-Station', 'C2C, Lay-duce',
       'Asahi Production, Rising Force', 'Shirogumi, Shin-Ei Animation',
       'Tatsunoko Production, 10Gauge', 'Circle Tribute',
       'J.C.Staff, A.C.G.T.', 'Jumondo', 'Lay-duce',
       'Project No.9, Tri-Slash', 'Studio Ghibli, Polygon Pictures',
       'Cyclone Graphics', 'Studio Comet, Zexcs', 'A-1 Pictures, TROYCA',
       'Satelight, C2C', 'Shuka', 'Studio 3Hz',
       'Studio Deen, Studio Hibari', 'Manglobe, Geno Studio', 'Shimogumi',
       'Mook Animation, Urban Product', 'Iyasakadou Film', 'Fuji TV',
       'Studio Deen, Wit Studio', 'Liberty Animation Studio',
       'Ordet, Studio Moriken', 'BreakBottle', 'MS Pictures',
       'Creators in Pack', 'Millepensee', 'Next Media Animation',
       'Dynamo Pictures', 'Pollyanna Graphics', 'J.C.Staff, Nomad',
       'Bandai Namco Pictures', 'TMS Entertainment, DLE',
       'Production I.G, DLE', 'Mili Pictures', 'J.C.Staff, SANZIGEN',
       'A-Real', 'TMS Entertainment, Telecom Animation Film',
       'Artland, Hoods Entertainment', "Steve N' Steven, Rockwell Eyes",
       'Calf Studio', 'Khara, Trigger, Studio Colorido',
       'Gathering, Asahi Production', 'Toei Animation, Bridge',
       'Shirogumi, Encourage Films', 'Khara, CyberConnect2',
       'Haoliners Animation League', 'Telecom Animation Film, Graphinica',
       'Ordet, Millepensee', 'Studio! Cucuri', 'EMT Squared',
       'TMS Entertainment, 3xCube', 'Kinema Citrus, White Fox',
       'MAPPA, Studio VOLN', 'TYMOTE', 'Media Bank', 'Studio A-CAT',
       "Steve N' Steven", 'TROYCA', 'Studio Animal', 'Lerche, 10Gauge',
       'SILVER LINK., Nexus', 'Barnum Studio, SILVER LINK., Connect',
       'Production I.G, OLM', 'L²Studio', 'Office DCI', 'Tomovies',
       'W-Toon Studio', 'Arms, Asread', 'ixtl, LIDENFILMS', 'Buemon',
       'Signal.MD', 'Actas, Bee Media', '10Gauge', 'Studio Ponoc',
       'Orange, Studio 3Hz', "Brain's Base, Platinum Vision",
       'Qualia Animation', 'Hoods Drifters Studio',
       'OLM, OLM Digital, Sprite Animation Studios',
       'TYO Animations, LIDENFILMS', 'AXsiZ', 'CygamesPictures',
       'Tatsunoko Production, CoMix Wave Films, FOREST Hunting One',
       'feel., Zexcs, Assez Finaud Fabric', 'Kyotoma, Office Nobu',
       'KOO-KI', 'Pie in the sky', 'Idea Factory',
       'Production IMS, Orange', 'Pine Jam', 'Kinema Citrus, EMT Squared',
       'Onionskin', 'Shanghai Foch Film Culture Investment',
       'Sakura Create', 'Gaina', 'Studio Gokumi, AXsiZ', 'Gainax, Gaina',
       'B.CMAY PICTURES', 'Xebec, Issen', 'Millepensee, GEMBA',
       'Seven Arcs, Seven Arcs Pictures',
       'W-Toon Studio, DMM.futureworks', 'October Media', 'KAGAYA Studio',
       'Bridge, Husio Studio', 'Joker Films', 'DR Movie', 'Nut',
       'Saigo no Shudan', 'Moss Design Unit', 'Kyotoma', 'Neft Film',
       'Zero-G', 'domerica',
       'Production I.G, Signal.MD, Production GoodBook',
       'Orange, Seven Arcs Pictures', 'Ordet, W-Toon Studio', 'Queen Bee',
       'Jumonji', 'EDGE', 'J.C.Staff, Egg Firm', 'production doA',
       'Haoliners Animation League, Pb Animation Co. Ltd.',
       'Production I.G, OLM, Signal.MD',
       'TMS Entertainment, Shin-Ei Animation', 'WAO World, Studio Live',
       'Team YokkyuFuman', 'Namu Animation', 'TUBA', 'LandQ studios',
       'OLM Digital, Signal.MD', 'Tengu Kobo', 'feel., PRA',
       'Platinum Vision', 'Blade', 'Artland, TNK', 'Composition Inc.',
       'Pops Inc.', 'Studio Ppuri', 'Studio M2',
       'Creators in Pack, Namu Animation', 'Chippai', 'Studio Dadashow',
       'Gathering, Lesprit', 'Sotsu',
       'TMS Entertainment, Jinnis Animation Studios',
       'Dwango, LIDENFILMS', 'Typhoon Graphics', 'Decovocal',
       'Zexcs, Studio A-CAT', 'PRA', 'Project No.9, A-Real',
       'Science SARU', 'Yamamura Animation, Inc.',
       'Production I.G, Xebec, I.Gzwei', 'Felix Film', 'Studio Zealot',
       'Asahi Production, Success Corp.', 'SELFISH', 'Rockwell Eyes',
       'Tomoyasu Murata Company', 'Karasfilms',
       'Gonzo, DandeLion Animation Studio', 'Chiptune', 'Twilight Studio',
       'Fanworks, Imagineer', 'Haoliners Animation League, Studio LAN',
       'drop', 'Shin-Ei Animation, DLE', 'iDRAGONS Creative Studio',
       'Oddjob', 'Actas, Studio 3Hz', 'Shirogumi, EMT Squared',
       "Children's Playground Entertainment", 'Craftar Studios',
       'Studio Khronos', 'CloverWorks', 'Orange',
       'Yokohama Animation Lab', 'Ruo Hong Culture',
       'Beijing Rocen Digital', 'Diomedéa, Studio Blanc', 'Emon, Blade',
       'Shaft, Tatsunoko Production', 'GEEK TOYS',
       'Production I.G, Nut, Revoroot',
       'A-1 Pictures, Trigger, CloverWorks', 'Bibury Animation Studios',
       'A-1 Pictures, Bridge, CloverWorks', 'Studio Flad',
       'G-Lam, Studio CA', 'Geno Studio', 'Studio VOLN', 'Studio LAN',
       'DandeLion Animation Studio', 'Pb Animation Co. Ltd., Studio LAN',
       'Directions', 'BigFireBird Animation', 'Akatsuki',
       'Sunrise, The Answer Studio', 'TNK, Zero-G', 'KIZAWA Studio',
       'Trigger, dwarf', 'NAZ, Magia Doraglier', 'Boyan Pictures',
       'Nice Boat Animation', 'pH Studio', 'D & D Pictures', 'CG Year',
       '2:10 AM Animation', 'Strawberry Meets Pictures',
       'Studio VOLN, Studio M2', 'Production I.G, Sola Digital Arts',
       'Asread, White Fox', 'OLM, Wit Studio',
       'Creators in Pack, Studio Lings', 'BOOTLEG', 'helo.inc',
       'UWAN Pictures', 'Tencent Animation & Comics', 'Thundray',
       'Wawayu Animation', 'EKACHI EPILKA', 'Guton Animation Studio',
       'Imagineer', 'Passione, Creators in Pack', 'TriF Studio', 'Ark',
       'Tencent Penguin Pictures, Fenz', 'ASK Animation Studio',
       'MAPPA, Lapin Track', 'Madhouse, DLE', 'Brio Animation', 'Connect',
       'Ezόla', 'Revoroot', 'GRIZZLY', 'Asread, Tear Studio',
       'Blade, Thundray', 'Fanworks, Tomovies', 'Gonzo, Stingray',
       'Seven Stone Entertainment', 'CLAP', 'SANZIGEN, DMM.futureworks',
       'Dancing CG Studio', 'Lesprit',
       'B.CMAY PICTURES, Colored-Pencil Animation Design',

In [111]:
anime_data_extracted["Studios"].value_counts()

Studios
Unknown                                              3511
Toei Animation                                        587
Sunrise                                               442
J.C.Staff                                             323
Madhouse                                              315
                                                     ...
Bones, Production I.G, Studio 4°C, Toei Animation       1
Future Planet, Beijing Huihuang Animation Company       1
Indeprox                                                1
Robot Communications                                    1
10Gauge, Studio DURIAN                                  1
Name: count, Length: 948, dtype: int64

In [112]:
anime_data_extracted.isnull()

       MAL_ID   Name  Score  Genres   Type  Aired  Studios  Source
0       False  False  False   False  False  False    False   False
1       False  False  False   False  False  False    False   False
2       False  False  False   False  False  False    False   False
3       False  False  False   False  False  False    False   False
4       False  False  False   False  False  False    False   False
...       ...    ...    ...     ...    ...    ...      ...     ...
17504   False  False  False   False  False  False    False   False
17505   False  False  False   False  False  False    False   False
17512   False  False  False   False  False  False    False   False
17513   False  False  False   False  False  False    False   False
17552   False  False  False   False  False  False    False   False

[12421 rows x 8 columns]

In [113]:
anime_data_extracted.isnull().sum()

MAL_ID     0
Name       0
Score      0
Genres     0
Type       0
Aired      0
Studios    0
Source     0
dtype: int64

In [114]:
anime_list.isnull().sum()

user_id             0
anime_id            0
rating              0
watching_status     0
watched_episodes    0
dtype: int64

In [115]:
anime_synop.isnull().sum()

MAL_ID       0
Name         0
Score        0
Genres       0
sypnopsis    8
dtype: int64

In [116]:
# Sort by index
anime_data_extracted.sort_index()

,MAL_ID,Name,Score,Genres,Type,Aired,Studios,Source
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,"Apr 3, 1998 to Apr 24, 1999",Sunrise,Original
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",Movie,"Sep 1, 2001",Bones,Original
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",TV,"Apr 1, 1998 to Sep 30, 1998",Madhouse,Manga
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",TV,"Jul 2, 2002 to Dec 24, 2002",Sunrise,Original
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",TV,"Sep 30, 2004 to Sep 29, 2005",Toei Animation,Manga
...,...,...,...,...,...,...,...,...
17504,47398,Kimetsu Gakuen: Valentine-hen,6.59,Comedy,ONA,"Feb 14, 2021",Unknown,Original
17505,47402,Heikousen,7.52,"Music, Romance",Music,"Feb 5, 2021","10Gauge, Studio DURIAN",Original
17512,47614,Nu Wushen de Canzhuo Spring Festival Special,6.83,"Slice of Life, Comedy",Special,"Feb 11, 2021",Unknown,Game
17513,47616,Yakusoku no Neverland 2nd Season: Michishirube,4.81,"Mystery, Psychological, Supernatural, Thriller...",Special,"Feb 12, 2021",CloverWorks,Manga
17552,48456,SK∞: Crazy Rock Jam,6.52,"Comedy, Sports",Special,"Mar 14, 2021",Bones,Original

In [117]:
# Sort by value
anime_data_extracted.sort_values(by='Score', ascending=False)

,MAL_ID,Name,Score,Genres,Type,Aired,Studios,Source
3971,5114,Fullmetal Alchemist: Brotherhood,9.19,"Action, Military, Adventure, Comedy, Drama, Ma...",TV,"Apr 5, 2009 to Jul 4, 2010",Bones,Manga
15926,40028,Shingeki no Kyojin: The Final Season,9.17,"Action, Military, Mystery, Super Power, Drama,...",TV,"Dec 7, 2020 to ?",MAPPA,Manga
5683,9253,Steins;Gate,9.11,"Thriller, Sci-Fi",TV,"Apr 6, 2011 to Sep 14, 2011",White Fox,Visual novel
14963,38524,Shingeki no Kyojin Season 3 Part 2,9.1,"Action, Drama, Fantasy, Military, Mystery, Sho...",TV,"Apr 29, 2019 to Jul 1, 2019",Wit Studio,Manga
9913,28977,Gintama°,9.1,"Action, Comedy, Historical, Parody, Samurai, S...",TV,"Apr 8, 2015 to Mar 30, 2016",Bandai Namco Pictures,Manga
...,...,...,...,...,...,...,...,...
4204,5569,Tsui no Sora,2.26,Hentai,OVA,"Aug 10, 2002",Unknown,Visual novel
387,413,Hametsu no Mars,2.23,"Sci-Fi, Horror",OVA,"Jul 6, 2005",WAO World,Visual novel
15172,38853,Ex-Arm,2.18,"Action, Sci-Fi, Ecchi, Seinen",TV,"Jan 11, 2021 to ?",Visual Flight,Manga
6967,13405,Utsu Musume Sayuri,2.01,"Comedy, Dementia",OVA,2003,Unknown,Original
2934,3287,Tenkuu Danzai Skelter+Heaven,1.85,"Sci-Fi, Mecha",OVA,"Dec 8, 2004",Unknown,Game

In [118]:
anime_data_extracted.sort_values(by='Score', ascending=False).tail()

,MAL_ID,Name,Score,Genres,Type,Aired,Studios,Source
4204,5569,Tsui no Sora,2.26,Hentai,OVA,"Aug 10, 2002",Unknown,Visual novel
387,413,Hametsu no Mars,2.23,"Sci-Fi, Horror",OVA,"Jul 6, 2005",WAO World,Visual novel
15172,38853,Ex-Arm,2.18,"Action, Sci-Fi, Ecchi, Seinen",TV,"Jan 11, 2021 to ?",Visual Flight,Manga
6967,13405,Utsu Musume Sayuri,2.01,"Comedy, Dementia",OVA,2003,Unknown,Original
2934,3287,Tenkuu Danzai Skelter+Heaven,1.85,"Sci-Fi, Mecha",OVA,"Dec 8, 2004",Unknown,Game

# 3.5 Merging and Concatenting Data

In [119]:
print(len(anime_data))
anime_data.head(3)

17562

,MAL_ID,Name,Score,Genres,English name,Japanese name,Type,Episodes,Aired,Premiered,Producers,Licensors,Studios,Source,Duration,Rating,Ranked,Popularity,Members,Favorites,Watching,Completed,On-Hold,Dropped,Plan to Watch,Score-10,Score-9,Score-8,Score-7,Score-6,Score-5,Score-4,Score-3,Score-2,Score-1
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",Cowboy Bebop,カウボーイビバップ,TV,26,"Apr 3, 1998 to Apr 24, 1999",Spring 1998,Bandai Visual,"Funimation, Bandai Entertainment",Sunrise,Original,24 min. per ep.,R - 17+ (violence & profanity),28.0,39,1251960,61971,105808,718161,71513,26678,329800,229170.0,182126.0,131625.0,62330.0,20688.0,8904.0,3184.0,1357.0,741.0,1580.0
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",Cowboy Bebop:The Movie,カウボーイビバップ 天国の扉,Movie,1,"Sep 1, 2001",Unknown,"Sunrise, Bandai Visual",Sony Pictures Entertainment,Bones,Original,1 hr. 55 min.,R - 17+ (violence & profanity),159.0,518,273145,1174,4143,208333,1935,770,57964,30043.0,49201.0,49505.0,22632.0,5805.0,1877.0,577.0,221.0,109.0,379.0
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",Trigun,トライガン,TV,26,"Apr 1, 1998 to Sep 30, 1998",Spring 1998,Victor Entertainment,"Funimation, Geneon Entertainment USA",Madhouse,Manga,24 min. per ep.,PG-13 - Teens 13 or older,266.0,201,558913,12944,29113,343492,25465,13925,146918,50229.0,75651.0,86142.0,49432.0,15376.0,5838.0,1965.0,664.0,316.0,533.0

In [120]:
print(len(anime_list))
anime_list.head(3)

499

   user_id  anime_id  rating  watching_status  watched_episodes
0        0        67       9                1                 1
1        0      6702       7                1                 4
2        0       242      10                1                 4

In [121]:
print(len(anime_synop))
anime_synop.head(3)

16214

,MAL_ID,Name,Score,Genres,sypnopsis
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space","In the year 2071, humanity has colonized sever..."
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space","other day, another bounty—such is the life of ..."
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen","Vash the Stampede is the man with a $$60,000,0..."

### 3.5.1 Merging Data
In this section, we will look at how to combine two sets of data. There are four possible ways to join data 1 and data 2.

(1) Inner join (INNER JOIN): Joins data when both have keys.

(2) Left outer join (LEFT JOIN): Joins when the data on the left side has a key.

(3) Right outer join (RIGHT JOIN): Joins when the key of the data is on the right side.

(4) Full outer join (FULL JOIN): Joins when the key exists on either side.

In [122]:
anime_data_extracted

,MAL_ID,Name,Score,Genres,Type,Aired,Studios,Source
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,"Apr 3, 1998 to Apr 24, 1999",Sunrise,Original
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",Movie,"Sep 1, 2001",Bones,Original
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",TV,"Apr 1, 1998 to Sep 30, 1998",Madhouse,Manga
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",TV,"Jul 2, 2002 to Dec 24, 2002",Sunrise,Original
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",TV,"Sep 30, 2004 to Sep 29, 2005",Toei Animation,Manga
...,...,...,...,...,...,...,...,...
17504,47398,Kimetsu Gakuen: Valentine-hen,6.59,Comedy,ONA,"Feb 14, 2021",Unknown,Original
17505,47402,Heikousen,7.52,"Music, Romance",Music,"Feb 5, 2021","10Gauge, Studio DURIAN",Original
17512,47614,Nu Wushen de Canzhuo Spring Festival Special,6.83,"Slice of Life, Comedy",Special,"Feb 11, 2021",Unknown,Game
17513,47616,Yakusoku no Neverland 2nd Season: Michishirube,4.81,"Mystery, Psychological, Supernatural, Thriller...",Special,"Feb 12, 2021",CloverWorks,Manga
17552,48456,SK∞: Crazy Rock Jam,6.52,"Comedy, Sports",Special,"Mar 14, 2021",Bones,Original

In [123]:
anime_synop

,MAL_ID,Name,Score,Genres,sypnopsis
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space","In the year 2071, humanity has colonized sever..."
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space","other day, another bounty—such is the life of ..."
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen","Vash the Stampede is the man with a $$60,000,0..."
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",ches are individuals with special powers like ...
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",It is the dark century and the people are suff...
...,...,...,...,...,...
16209,48481,Daomu Biji Zhi Qinling Shen Shu,Unknown,"Adventure, Mystery, Supernatural",No synopsis information has been added to this...
16210,48483,Mieruko-chan,Unknown,"Comedy, Horror, Supernatural",ko is a typical high school student whose life...
16211,48488,Higurashi no Naku Koro ni Sotsu,Unknown,"Mystery, Dementia, Horror, Psychological, Supe...",Sequel to Higurashi no Naku Koro ni Gou .
16212,48491,Yama no Susume: Next Summit,Unknown,"Adventure, Slice of Life, Comedy",New Yama no Susume anime.
16213,48492,Scarlet Nexus,Unknown,"Action, Fantasy",Solar calendar year 2020: grotesque organisms ...

In [124]:
# Data merging (inner join)
# Keys are automatically recognized
pd.merge(anime_data_extracted, anime_synop)

,MAL_ID,Name,Score,Genres,Type,Aired,Studios,Source,sypnopsis
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,"Apr 3, 1998 to Apr 24, 1999",Sunrise,Original,"In the year 2071, humanity has colonized sever..."
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",Movie,"Sep 1, 2001",Bones,Original,"other day, another bounty—such is the life of ..."
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",TV,"Apr 1, 1998 to Sep 30, 1998",Madhouse,Manga,"Vash the Stampede is the man with a $$60,000,0..."
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",TV,"Jul 2, 2002 to Dec 24, 2002",Sunrise,Original,ches are individuals with special powers like ...
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",TV,"Sep 30, 2004 to Sep 29, 2005",Toei Animation,Manga,It is the dark century and the people are suff...
...,...,...,...,...,...,...,...,...,...
11086,47398,Kimetsu Gakuen: Valentine-hen,6.59,Comedy,ONA,"Feb 14, 2021",Unknown,Original,Valentine's Day special for Kimetsu no Yaiba ....
11087,47402,Heikousen,7.52,"Music, Romance",Music,"Feb 5, 2021","10Gauge, Studio DURIAN",Original,"usic video for Eve and suis' song Heikousen , ..."
11088,47614,Nu Wushen de Canzhuo Spring Festival Special,6.83,"Slice of Life, Comedy",Special,"Feb 11, 2021",Unknown,Game,No synopsis information has been added to this...
11089,47616,Yakusoku no Neverland 2nd Season: Michishirube,4.81,"Mystery, Psychological, Supernatural, Thriller...",Special,"Feb 12, 2021",CloverWorks,Manga,cap of the first season of Yakusoku no Neverla...
11090,48456,SK∞: Crazy Rock Jam,6.52,"Comedy, Sports",Special,"Mar 14, 2021",Bones,Original,cap of the first 9 episodes of SK∞ .

In [125]:
# Data merging (inner join)
# Keys to merge can be specified explicitly using "on"
pd.merge(anime_data_extracted, anime_synop, on='MAL_ID')

,MAL_ID,Name_x,Score_x,Genres_x,Type,Aired,Studios,Source,Name_y,Score_y,Genres_y,sypnopsis
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,"Apr 3, 1998 to Apr 24, 1999",Sunrise,Original,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space","In the year 2071, humanity has colonized sever..."
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",Movie,"Sep 1, 2001",Bones,Original,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space","other day, another bounty—such is the life of ..."
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",TV,"Apr 1, 1998 to Sep 30, 1998",Madhouse,Manga,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen","Vash the Stampede is the man with a $$60,000,0..."
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",TV,"Jul 2, 2002 to Dec 24, 2002",Sunrise,Original,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",ches are individuals with special powers like ...
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",TV,"Sep 30, 2004 to Sep 29, 2005",Toei Animation,Manga,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",It is the dark century and the people are suff...
...,...,...,...,...,...,...,...,...,...,...,...,...
11086,47398,Kimetsu Gakuen: Valentine-hen,6.59,Comedy,ONA,"Feb 14, 2021",Unknown,Original,Kimetsu Gakuen: Valentine-hen,6.59,Comedy,Valentine's Day special for Kimetsu no Yaiba ....
11087,47402,Heikousen,7.52,"Music, Romance",Music,"Feb 5, 2021","10Gauge, Studio DURIAN",Original,Heikousen,7.52,"Music, Romance","usic video for Eve and suis' song Heikousen , ..."
11088,47614,Nu Wushen de Canzhuo Spring Festival Special,6.83,"Slice of Life, Comedy",Special,"Feb 11, 2021",Unknown,Game,Nu Wushen de Canzhuo Spring Festival Special,6.83,"Slice of Life, Comedy",No synopsis information has been added to this...
11089,47616,Yakusoku no Neverland 2nd Season: Michishirube,4.81,"Mystery, Psychological, Supernatural, Thriller...",Special,"Feb 12, 2021",CloverWorks,Manga,Yakusoku no Neverland 2nd Season: Michishirube,4.81,"Mystery, Psychological, Supernatural, Thriller...",cap of the first season of Yakusoku no Neverla...
11090,48456,SK∞: Crazy Rock Jam,6.52,"Comedy, Sports",Special,"Mar 14, 2021",Bones,Original,SK∞: Crazy Rock Jam,6.52,"Comedy, Sports",cap of the first 9 episodes of SK∞ .

In [127]:
anime_list.head()

   user_id  anime_id  rating  watching_status  watched_episodes
0        0        67       9                1                 1
1        0      6702       7                1                 4
2        0       242      10                1                 4
3        0      4898       0                1                 1
4        0        21      10                1                 0

In [133]:
anime_data_extracted.head()

,MAL_ID,Name,Score,Genres,Type,Aired,Studios,Source
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,"Apr 3, 1998 to Apr 24, 1999",Sunrise,Original
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",Movie,"Sep 1, 2001",Bones,Original
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",TV,"Apr 1, 1998 to Sep 30, 1998",Madhouse,Manga
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",TV,"Jul 2, 2002 to Dec 24, 2002",Sunrise,Original
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",TV,"Sep 30, 2004 to Sep 29, 2005",Toei Animation,Manga

In [134]:
print(anime_data_extracted.shape)

(12421, 8)

The `left_on` and `right_on` arguments can be used to specify keys individually. In addition, the `left_index` and `right_index` arguments can be used to specify and join by `Index`.

The following example merges `anime_list` and `anime_data`, using `anime_id` and `MAL_ID` columns, respectively, as keys.

In [126]:
pd.merge(anime_list, anime_data_extracted, left_on='anime_id', right_on='MAL_ID')

,user_id,anime_id,rating,watching_status,watched_episodes,MAL_ID,Name,Score,Genres,Type,Aired,Studios,Source
0,0,67,9,1,1,67,Basilisk: Kouga Ninpou Chou,7.58,"Action, Adventure, Historical, Supernatural, R...",TV,"Apr 13, 2005 to Sep 21, 2005",Gonzo,Manga
1,0,6702,7,1,4,6702,Fairy Tail,7.68,"Action, Adventure, Comedy, Magic, Fantasy, Sho...",TV,"Oct 12, 2009 to Mar 30, 2013","Satelight, A-1 Pictures",Manga
2,0,242,10,1,4,242,Gokusen,7.42,"Slice of Life, Comedy, Drama, School, Josei",TV,"Jan 6, 2004 to Mar 30, 2004",Madhouse,Manga
3,0,4898,0,1,1,4898,Kuroshitsuji,7.75,"Action, Mystery, Comedy, Historical, Demons, S...",TV,"Oct 3, 2008 to Mar 27, 2009",A-1 Pictures,Manga
4,0,21,10,1,0,21,One Piece,8.52,"Action, Adventure, Comedy, Super Power, Drama,...",TV,"Oct 20, 1999 to ?",Toei Animation,Manga
...,...,...,...,...,...,...,...,...,...,...,...,...,...
487,2,9588,0,6,0,9588,Kyouiku Shidou The Animation,6.31,Hentai,OVA,"Nov 19, 2010",Studio Eromatick,Visual novel
488,2,10325,0,6,0,10325,Kyuuketsuki,5.93,"Hentai, Vampire",OVA,"Mar 11, 2011 to Dec 21, 2012",Unknown,Visual novel
489,2,8111,0,6,0,8111,Last Waltz: Hakudaku Mamire no Natsu Gasshuku,6.32,Hentai,OVA,"Apr 30, 2010 to Oct 29, 2010",Unknown,Visual novel
490,2,37939,0,6,0,37939,Lilitales,6.07,Hentai,OVA,"May 18, 2018 to Jun 29, 2018",SELFISH,Game
491,2,11969,0,6,0,11969,Love Bitch: Yasashii Onna,6.24,Hentai,OVA,"Dec 22, 2011",Unknown,Manga

### Left Outer join

In [135]:
# Preparing data 1
data1 = {
    'id': ['100', '101', '102', '103', '104', '106', '108', '110', '111',' 113'],
    'city': ['Tokyo', 'Osaka', 'Kyoto', 'Hokkaido', 'Tokyo', 'Tokyo', 'Osaka', 'Kyoto', 'Hokkaido', 'Tokyo'],
    'birth_year': [1990, 1989, 1992, 1997, 1982, 1991, 1988, 1990, 1995, 1981],
    'name': ['Hiroshi', 'Akiko', 'Yuki', 'Satoru', 'Steeve', 'Mituru', 'Aoi', 'Tarou', 'Suguru','Mitsuo']
}
df1 = DataFrame(data1)
df1

     id      city  birth_year     name
0   100     Tokyo        1990  Hiroshi
1   101     Osaka        1989    Akiko
2   102     Kyoto        1992     Yuki
3   103  Hokkaido        1997   Satoru
4   104     Tokyo        1982   Steeve
5   106     Tokyo        1991   Mituru
6   108     Osaka        1988      Aoi
7   110     Kyoto        1990    Tarou
8   111  Hokkaido        1995   Suguru
9   113     Tokyo        1981   Mitsuo

In [136]:
# Preparing data 2
data2 = {
    'id': ['100', '101', '102', '105', '107'],
    'math': [50, 43, 33, 76, 98],
    'english': [90, 30, 20, 50, 30],
    'sex': ['M','F','F','M','M'],
    'index_num': [0, 1, 2, 3, 4]
}
df2 = DataFrame(data2)
df2

    id  math  english sex  index_num
0  100    50       90   M          0
1  101    43       30   F          1
2  102    33       20   F          2
3  105    76       50   M          3
4  107    98       30   M          4

In [138]:
df1.shape, df2.shape

((10, 4), (5, 5))

In [139]:
# Data merge（left outer join）
pd.merge(df1, df2, how='left')

     id      city  birth_year     name  math  english  sex  index_num
0   100     Tokyo        1990  Hiroshi  50.0     90.0    M        0.0
1   101     Osaka        1989    Akiko  43.0     30.0    F        1.0
2   102     Kyoto        1992     Yuki  33.0     20.0    F        2.0
3   103  Hokkaido        1997   Satoru   NaN      NaN  NaN        NaN
4   104     Tokyo        1982   Steeve   NaN      NaN  NaN        NaN
5   106     Tokyo        1991   Mituru   NaN      NaN  NaN        NaN
6   108     Osaka        1988      Aoi   NaN      NaN  NaN        NaN
7   110     Kyoto        1990    Tarou   NaN      NaN  NaN        NaN
8   111  Hokkaido        1995   Suguru   NaN      NaN  NaN        NaN
9   113     Tokyo        1981   Mitsuo   NaN      NaN  NaN        NaN

In [140]:
# Data merge（left outer join）
pd.merge(df2, df1, how='left')

    id  math  english sex  index_num   city  birth_year     name
0  100    50       90   M          0  Tokyo      1990.0  Hiroshi
1  101    43       30   F          1  Osaka      1989.0    Akiko
2  102    33       20   F          2  Kyoto      1992.0     Yuki
3  105    76       50   M          3    NaN         NaN      NaN
4  107    98       30   M          4    NaN         NaN      NaN

In [141]:
# Data merge（Full outer join）
pd.merge(df1, df2, how='outer')

      id      city  birth_year     name  math  english  sex  index_num
0    113     Tokyo      1981.0   Mitsuo   NaN      NaN  NaN        NaN
1    100     Tokyo      1990.0  Hiroshi  50.0     90.0    M        0.0
2    101     Osaka      1989.0    Akiko  43.0     30.0    F        1.0
3    102     Kyoto      1992.0     Yuki  33.0     20.0    F        2.0
4    103  Hokkaido      1997.0   Satoru   NaN      NaN  NaN        NaN
..   ...       ...         ...      ...   ...      ...  ...        ...
7    106     Tokyo      1991.0   Mituru   NaN      NaN  NaN        NaN
8    107       NaN         NaN      NaN  98.0     30.0    M        4.0
9    108     Osaka      1988.0      Aoi   NaN      NaN  NaN        NaN
10   110     Kyoto      1990.0    Tarou   NaN      NaN  NaN        NaN
11   111  Hokkaido      1995.0   Suguru   NaN      NaN  NaN        NaN

[12 rows x 8 columns]

In [142]:
pd.merge(df1, df2, how='outer').shape

(12, 8)

## 3.5.2 Concatenating Data

In [143]:
# Prepare Data 3
data3 = {
    'id': ['117', '118', '119', '120', '125'],
    'city': ['Chiba', 'Kanagawa', 'Tokyo', 'Fukuoka', 'Okinawa'],
    'birth_year': [1990, 1989, 1992, 1997, 1982],
    'name': ['Suguru', 'Kouichi', 'Satochi', 'Yukie', 'Akari']
}
df3 = DataFrame(data3)
df3

    id      city  birth_year     name
0  117     Chiba        1990   Suguru
1  118  Kanagawa        1989  Kouichi
2  119     Tokyo        1992  Satochi
3  120   Fukuoka        1997    Yukie
4  125   Okinawa        1982    Akari

In [144]:
df1

     id      city  birth_year     name
0   100     Tokyo        1990  Hiroshi
1   101     Osaka        1989    Akiko
2   102     Kyoto        1992     Yuki
3   103  Hokkaido        1997   Satoru
4   104     Tokyo        1982   Steeve
5   106     Tokyo        1991   Mituru
6   108     Osaka        1988      Aoi
7   110     Kyoto        1990    Tarou
8   111  Hokkaido        1995   Suguru
9   113     Tokyo        1981   Mitsuo

In [145]:
# concat vertically
pd.concat([df1, df3])

     id      city  birth_year     name
0   100     Tokyo        1990  Hiroshi
1   101     Osaka        1989    Akiko
2   102     Kyoto        1992     Yuki
3   103  Hokkaido        1997   Satoru
4   104     Tokyo        1982   Steeve
..  ...       ...         ...      ...
0   117     Chiba        1990   Suguru
1   118  Kanagawa        1989  Kouichi
2   119     Tokyo        1992  Satochi
3   120   Fukuoka        1997    Yukie
4   125   Okinawa        1982    Akari

[15 rows x 4 columns]

In [146]:
pd.concat([df1, df3], ignore_index=True)

     id      city  birth_year     name
0   100     Tokyo        1990  Hiroshi
1   101     Osaka        1989    Akiko
2   102     Kyoto        1992     Yuki
3   103  Hokkaido        1997   Satoru
4   104     Tokyo        1982   Steeve
..  ...       ...         ...      ...
10  117     Chiba        1990   Suguru
11  118  Kanagawa        1989  Kouichi
12  119     Tokyo        1992  Satochi
13  120   Fukuoka        1997    Yukie
14  125   Okinawa        1982    Akari

[15 rows x 4 columns]

In [147]:
# In case of sort = True
pd.concat([df1, df2], sort=True)

    birth_year      city  english   id  index_num  math     name  sex
0       1990.0     Tokyo      NaN  100        NaN   NaN  Hiroshi  NaN
1       1989.0     Osaka      NaN  101        NaN   NaN    Akiko  NaN
2       1992.0     Kyoto      NaN  102        NaN   NaN     Yuki  NaN
3       1997.0  Hokkaido      NaN  103        NaN   NaN   Satoru  NaN
4       1982.0     Tokyo      NaN  104        NaN   NaN   Steeve  NaN
..         ...       ...      ...  ...        ...   ...      ...  ...
0          NaN       NaN     90.0  100        0.0  50.0      NaN    M
1          NaN       NaN     30.0  101        1.0  43.0      NaN    F
2          NaN       NaN     20.0  102        2.0  33.0      NaN    F
3          NaN       NaN     50.0  105        3.0  76.0      NaN    M
4          NaN       NaN     30.0  107        4.0  98.0      NaN    M

[15 rows x 8 columns]

#### Horizontal Join
To join horizontally, specify an axis for the `axis` argument. The `axis=0` is the row and `axis=1` is the column. So here you need to specify `axis=1`. In this case, they will be tied by `index` and the `columns` will be joined as they are. If `axis=0` is specified, the columns will be joined vertically. Keep in mind that this `axis` argument is used in other situations as well.

In [148]:
pd.concat([df1, df2], axis=1)

     id      city  birth_year     name   id  math  english  sex  index_num
0   100     Tokyo        1990  Hiroshi  100  50.0     90.0    M        0.0
1   101     Osaka        1989    Akiko  101  43.0     30.0    F        1.0
2   102     Kyoto        1992     Yuki  102  33.0     20.0    F        2.0
3   103  Hokkaido        1997   Satoru  105  76.0     50.0    M        3.0
4   104     Tokyo        1982   Steeve  107  98.0     30.0    M        4.0
5   106     Tokyo        1991   Mituru  NaN   NaN      NaN  NaN        NaN
6   108     Osaka        1988      Aoi  NaN   NaN      NaN  NaN        NaN
7   110     Kyoto        1990    Tarou  NaN   NaN      NaN  NaN        NaN
8   111  Hokkaido        1995   Suguru  NaN   NaN      NaN  NaN        NaN
9   113     Tokyo        1981   Mitsuo  NaN   NaN      NaN  NaN        NaN

# 3.6 Manipulating and Transforming Data

In [162]:
# Delete rows in data
# axis=0 is set by default
anime_data_extracted.drop(index=[0,2]).head()

,MAL_ID,Name,Score,Genres,Type,Aired,Studios,Source
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",Movie,"Sep 1, 2001",Bones,Original
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",TV,"Jul 2, 2002 to Dec 24, 2002",Sunrise,Original
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",TV,"Sep 30, 2004 to Sep 29, 2005",Toei Animation,Manga
5,15,Eyeshield 21,7.95,"Action, Sports, Comedy, Shounen",TV,"Apr 6, 2005 to Mar 19, 2008",Gallop,Manga
6,16,Hachimitsu to Clover,8.06,"Comedy, Drama, Josei, Romance, Slice of Life",TV,"Apr 15, 2005 to Sep 27, 2005",J.C.Staff,Manga

Here, the `Index` is no longer continuous because a row has been deleted. So let's use `DataFrame.reset_index()` to reassign a new `Index`.

In [163]:
anime_data_extracted.drop(index=[0,2]).reset_index().head()

,index,MAL_ID,Name,Score,Genres,Type,Aired,Studios,Source
0,1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",Movie,"Sep 1, 2001",Bones,Original
1,3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",TV,"Jul 2, 2002 to Dec 24, 2002",Sunrise,Original
2,4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",TV,"Sep 30, 2004 to Sep 29, 2005",Toei Animation,Manga
3,5,15,Eyeshield 21,7.95,"Action, Sports, Comedy, Shounen",TV,"Apr 6, 2005 to Mar 19, 2008",Gallop,Manga
4,6,16,Hachimitsu to Clover,8.06,"Comedy, Drama, Josei, Romance, Slice of Life",TV,"Apr 15, 2005 to Sep 27, 2005",J.C.Staff,Manga

In [164]:
# Delete column in data
anime_data_extracted.drop(['Studios'], axis=1).head()

,MAL_ID,Name,Score,Genres,Type,Aired,Source
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,"Apr 3, 1998 to Apr 24, 1999",Original
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",Movie,"Sep 1, 2001",Original
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",TV,"Apr 1, 1998 to Sep 30, 1998",Manga
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",TV,"Jul 2, 2002 to Dec 24, 2002",Original
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",TV,"Sep 30, 2004 to Sep 29, 2005",Manga

# 3.6.2 Removing Duplicates

In [170]:
anime_data_extracted["Name"].duplicated().sum()

np.int64(1)

In [171]:
anime_data_extracted[anime_data_extracted["Name"].duplicated()] # this is duplicate entry

,MAL_ID,Name,Score,Genres,Type,Aired,Studios,Source
13540,36296,Hinamatsuri,8.21,"Comedy, Sci-Fi, Seinen, Slice of Life, Superna...",TV,"Apr 6, 2018 to Jun 22, 2018",feel.,Manga

In [172]:
anime_data_extracted["Name"].drop_duplicates().isnull().sum()

np.int64(0)

In [173]:
anime_data_extracted[anime_data_extracted["Name"].duplicated()] # this is duplicate entry

,MAL_ID,Name,Score,Genres,Type,Aired,Studios,Source
13540,36296,Hinamatsuri,8.21,"Comedy, Sci-Fi, Seinen, Slice of Life, Superna...",TV,"Apr 6, 2018 to Jun 22, 2018",feel.,Manga

# 3.6.3 Mapping

In [174]:
# Reference data
status_map = {
    1: "Watching",
    2: "Completed",
    3: "On-Hold",
    4: "Dropped",
    6: "Plan to Watch"
}
status_map

{1: 'Watching', 2: 'Completed', 3: 'On-Hold', 4: 'Dropped', 6: 'Plan to Watch'}

In [175]:
# Drop invalid rows first
invalid_status = [0, 5, 33, 55]
# Use ~ to represent NOT
anime_list = anime_list[~anime_list['watching_status'].isin(invalid_status)]

anime_list["status_label"] = anime_list["watching_status"].map(status_map)
anime_list

,user_id,anime_id,rating,watching_status,watched_episodes,status_label
0,0,67,9,1,1,Watching
1,0,6702,7,1,4,Watching
2,0,242,10,1,4,Watching
3,0,4898,0,1,1,Watching
4,0,21,10,1,0,Watching
...,...,...,...,...,...,...
494,2,9588,0,6,0,Plan to Watch
495,2,10325,0,6,0,Plan to Watch
496,2,8111,0,6,0,Plan to Watch
497,2,37939,0,6,0,Plan to Watch
498,2,11969,0,6,0,Plan to Watch

In [176]:
# we need to convert score to float type first
anime_data_extracted["Score"] = anime_data_extracted["Score"].astype(float)

anime_data_extracted['ScoreCategory'] = anime_data_extracted['Score'].map(
    lambda x: 'Low' if x < 5 else ('Average' if x <= 7 else 'High')
)
anime_data_extracted.head()

,MAL_ID,Name,Score,Genres,Type,Aired,Studios,Source,ScoreCategory
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,"Apr 3, 1998 to Apr 24, 1999",Sunrise,Original,High
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",Movie,"Sep 1, 2001",Bones,Original,High
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",TV,"Apr 1, 1998 to Sep 30, 1998",Madhouse,Manga,High
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",TV,"Jul 2, 2002 to Dec 24, 2002",Sunrise,Original,High
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",TV,"Sep 30, 2004 to Sep 29, 2005",Toei Animation,Manga,Average